class CountryDataStore {
  static const List<Map<String, dynamic>> _countries = [
    {
      "name_es": "Argelia",
      "name_ar": "الجزائر",
      "name_fr": "Algérie",
      "name_zh": "阿尔及利亚",
      "name_ru": "Алжир",
      "name_en": "Algeria",
      "M49 Code": 12,
      "ISO-alpha2 Code": "DZ",
      "ISO-alpha3 Code": "DZA",
      "name_pt": "Argélia"
    },
    {
      "name_es": "Egipto",
      "name_ar": "مصر",
      "name_fr": "Égypte",
      "name_zh": "埃及",
      "name_ru": "Египет",
      "name_en": "Egypt",
      "M49 Code": 818,
      "ISO-alpha2 Code": "EG",
      "ISO-alpha3 Code": "EGY",
      "name_pt": "Egito"
    },
    {
      "name_es": "Libia",
      "name_ar": "ليبيا",
      "name_fr": "Libye",
      "name_zh": "利比亚",
      "name_ru": "Ливия",
      "name_en": "Libya",
      "M49 Code": 434,
      "ISO-alpha2 Code": "LY",
      "ISO-alpha3 Code": "LBY",
      "name_pt": "Líbia"
    },
    {
      "name_es": "Marruecos",
      "name_ar": "المغرب",
      "name_fr": "Maroc",
      "name_zh": "摩洛哥",
      "name_ru": "Марокко",
      "name_en": "Morocco",
      "M49 Code": 504,
      "ISO-alpha2 Code": "MA",
      "ISO-alpha3 Code": "MAR",
      "name_pt": "Marrocos"
    },
    {
      "name_es": "Sudán",
      "name_ar": "السودان",
      "name_fr": "Soudan",
      "name_zh": "苏丹",
      "name_ru": "Судан",
      "name_en": "Sudan",
      "M49 Code": 729,
      "ISO-alpha2 Code": "SD",
      "ISO-alpha3 Code": "SDN",
      "name_pt": "Sudão"
    },
    {
      "name_es": "Túnez",
      "name_ar": "تونس",
      "name_fr": "Tunisie",
      "name_zh": "突尼斯",
      "name_ru": "Тунис",
      "name_en": "Tunisia",
      "M49 Code": 788,
      "ISO-alpha2 Code": "TN",
      "ISO-alpha3 Code": "TUN",
      "name_pt": "Tunísia"
    },
    {
      "name_es": "Sáhara Occidental",
      "name_ar": "الصحراء الغربية",
      "name_fr": "Sahara occidental",
      "name_zh": "西撒哈拉",
      "name_ru": "Западная Сахара",
      "name_en": "Western Sahara",
      "M49 Code": 732,
      "ISO-alpha2 Code": "EH",
      "ISO-alpha3 Code": "ESH",
      "name_pt": "Saara Ocidental"
    },
    {
      "name_es": "Territorio Británico del Océano Índico",
      "name_ar": "المحيط الهندي الإقليم البريطاني في",
      "name_fr": "Territoire britannique de l'océan Indien",
      "name_zh": "英属印度洋领土",
      "name_ru": "Британская территория в Индийском океане",
      "name_en": "British Indian Ocean Territory",
      "M49 Code": 86,
      "ISO-alpha2 Code": "IO",
      "ISO-alpha3 Code": "IOT",
      "name_pt": "Território Britânico do Oceano Índico"
    },
    {
      "name_es": "Burundi",
      "name_ar": "بوروندي",
      "name_fr": "Burundi",
      "name_zh": "布隆迪",
      "name_ru": "Бурунди",
      "name_en": "Burundi",
      "M49 Code": 108,
      "ISO-alpha2 Code": "BI",
      "ISO-alpha3 Code": "BDI",
      "name_pt": "Burundi"
    },
    {
      "name_es": "Comoras",
      "name_ar": "جزر القمر",
      "name_fr": "Comores",
      "name_zh": "科摩罗",
      "name_ru": "Коморские Острова",
      "name_en": "Comoros",
      "M49 Code": 174,
      "ISO-alpha2 Code": "KM",
      "ISO-alpha3 Code": "COM",
      "name_pt": "Comores"
    },
    {
      "name_es": "Djibouti",
      "name_ar": "جيبوتي",
      "name_fr": "Djibouti",
      "name_zh": "吉布提",
      "name_ru": "Джибути",
      "name_en": "Djibouti",
      "M49 Code": 262,
      "ISO-alpha2 Code": "DJ",
      "ISO-alpha3 Code": "DJI",
      "name_pt": "Djibuti"
    },
    {
      "name_es": "Eritrea",
      "name_ar": "إريتريا",
      "name_fr": "Érythrée",
      "name_zh": "厄立特里亚",
      "name_ru": "Эритрея",
      "name_en": "Eritrea",
      "M49 Code": 232,
      "ISO-alpha2 Code": "ER",
      "ISO-alpha3 Code": "ERI",
      "name_pt": "Eritreia"
    },
    {
      "name_es": "Etiopía",
      "name_ar": "إثيوبيا",
      "name_fr": "Éthiopie",
      "name_zh": "埃塞俄比亚",
      "name_ru": "Эфиопия",
      "name_en": "Ethiopia",
      "M49 Code": 231,
      "ISO-alpha2 Code": "ET",
      "ISO-alpha3 Code": "ETH",
      "name_pt": "Etiópia"
    },
    {
      "name_es": "Territorio de las Tierras Australes Francesas",
      "name_ar": "الأراضي الفرنسية الجنوبية الجنوبية",
      "name_fr": "Terres australes françaises",
      "name_zh": "法属南方领地",
      "name_ru": "Южные земли (французская заморская территория)",
      "name_en": "French Southern Territories",
      "M49 Code": 260,
      "ISO-alpha2 Code": "TF",
      "ISO-alpha3 Code": "ATF",
      "name_pt": "Territórios Franceses do Sul"
    },
    {
      "name_es": "Kenya",
      "name_ar": "كينيا",
      "name_fr": "Kenya",
      "name_zh": "肯尼亚",
      "name_ru": "Кения",
      "name_en": "Kenya",
      "M49 Code": 404,
      "ISO-alpha2 Code": "KE",
      "ISO-alpha3 Code": "KEN",
      "name_pt": "Quênia"
    },
    {
      "name_es": "Madagascar",
      "name_ar": "مدغشقر",
      "name_fr": "Madagascar",
      "name_zh": "马达加斯加",
      "name_ru": "Мадагаскар",
      "name_en": "Madagascar",
      "M49 Code": 450,
      "ISO-alpha2 Code": "MG",
      "ISO-alpha3 Code": "MDG",
      "name_pt": "Madagáscar"
    },
    {
      "name_es": "Malawi",
      "name_ar": "ملاوي",
      "name_fr": "Malawi",
      "name_zh": "马拉维",
      "name_ru": "Малави",
      "name_en": "Malawi",
      "M49 Code": 454,
      "ISO-alpha2 Code": "MW",
      "ISO-alpha3 Code": "MWI",
      "name_pt": "Malawi"
    },
    {
      "name_es": "Mauricio",
      "name_ar": "موريشيوس",
      "name_fr": "Maurice",
      "name_zh": "毛里求斯",
      "name_ru": "Маврикий",
      "name_en": "Mauritius",
      "M49 Code": 480,
      "ISO-alpha2 Code": "MU",
      "ISO-alpha3 Code": "MUS",
      "name_pt": "Maurício"
    },
    {
      "name_es": "Mayotte",
      "name_ar": "مايوت",
      "name_fr": "Mayotte",
      "name_zh": "马约特",
      "name_ru": "Остров Майотта",
      "name_en": "Mayotte",
      "M49 Code": 175,
      "ISO-alpha2 Code": "YT",
      "ISO-alpha3 Code": "MYT",
      "name_pt": "Mayotte"
    },
    {
      "name_es": "Mozambique",
      "name_ar": "موزامبيق",
      "name_fr": "Mozambique",
      "name_zh": "莫桑比克",
      "name_ru": "Мозамбик",
      "name_en": "Mozambique",
      "M49 Code": 508,
      "ISO-alpha2 Code": "MZ",
      "ISO-alpha3 Code": "MOZ",
      "name_pt": "Moçambique"
    },
    {
      "name_es": "Reunión",
      "name_ar": "ريونيون",
      "name_fr": "Réunion",
      "name_zh": "留尼汪",
      "name_ru": "Реюньон",
      "name_en": "Réunion",
      "M49 Code": 638,
      "ISO-alpha2 Code": "RE",
      "ISO-alpha3 Code": "REU",
      "name_pt": "Reunião"
    },
    {
      "name_es": "Rwanda",
      "name_ar": "رواندا",
      "name_fr": "Rwanda",
      "name_zh": "卢旺达",
      "name_ru": "Руанда",
      "name_en": "Rwanda",
      "M49 Code": 646,
      "ISO-alpha2 Code": "RW",
      "ISO-alpha3 Code": "RWA",
      "name_pt": "Ruanda"
    },
    {
      "name_es": "Seychelles",
      "name_ar": "سيشيل",
      "name_fr": "Seychelles",
      "name_zh": "塞舌尔",
      "name_ru": "Сейшельские Острова",
      "name_en": "Seychelles",
      "M49 Code": 690,
      "ISO-alpha2 Code": "SC",
      "ISO-alpha3 Code": "SYC",
      "name_pt": "Seicheles"
    },
    {
      "name_es": "Somalia",
      "name_ar": "الصومال",
      "name_fr": "Somalie",
      "name_zh": "索马里",
      "name_ru": "Сомали",
      "name_en": "Somalia",
      "M49 Code": 706,
      "ISO-alpha2 Code": "SO",
      "ISO-alpha3 Code": "SOM",
      "name_pt": "Somália"
    },
    {
      "name_es": "Sudán del Sur",
      "name_ar": "جنوب السودان",
      "name_fr": "Soudan du Sud",
      "name_zh": "南苏丹",
      "name_ru": "Южный Судан",
      "name_en": "South Sudan",
      "M49 Code": 728,
      "ISO-alpha2 Code": "SS",
      "ISO-alpha3 Code": "SSD",
      "name_pt": "Sudão do Sul"
    },
    {
      "name_es": "Uganda",
      "name_ar": "أوغندا",
      "name_fr": "Ouganda",
      "name_zh": "乌干达",
      "name_ru": "Уганда",
      "name_en": "Uganda",
      "M49 Code": 800,
      "ISO-alpha2 Code": "UG",
      "ISO-alpha3 Code": "UGA",
      "name_pt": "Uganda"
    },
    {
      "name_es": "República Unida de Tanzanía",
      "name_ar": "جمهورية تنزانيا المتحدة",
      "name_fr": "République-Unie de Tanzanie",
      "name_zh": "坦桑尼亚联合共和国",
      "name_ru": "Объединенная Республика Танзания",
      "name_en": "United Republic of Tanzania",
      "M49 Code": 834,
      "ISO-alpha2 Code": "TZ",
      "ISO-alpha3 Code": "TZA",
      "name_pt": "República Unida da Tanzânia"
    },
    {
      "name_es": "Zambia",
      "name_ar": "زامبيا",
      "name_fr": "Zambie",
      "name_zh": "赞比亚",
      "name_ru": "Замбия",
      "name_en": "Zambia",
      "M49 Code": 894,
      "ISO-alpha2 Code": "ZM",
      "ISO-alpha3 Code": "ZMB",
      "name_pt": "Zâmbia"
    },
    {
      "name_es": "Zimbabwe",
      "name_ar": "زمبابوي",
      "name_fr": "Zimbabwe",
      "name_zh": "津巴布韦",
      "name_ru": "Зимбабве",
      "name_en": "Zimbabwe",
      "M49 Code": 716,
      "ISO-alpha2 Code": "ZW",
      "ISO-alpha3 Code": "ZWE",
      "name_pt": "Zimbábue"
    },
    {
      "name_es": "Angola",
      "name_ar": "أنغولا",
      "name_fr": "Angola",
      "name_zh": "安哥拉",
      "name_ru": "Ангола",
      "name_en": "Angola",
      "M49 Code": 24,
      "ISO-alpha2 Code": "AO",
      "ISO-alpha3 Code": "AGO",
      "name_pt": "Angola"
    },
    {
      "name_es": "Camerún",
      "name_ar": "الكاميرون",
      "name_fr": "Cameroun",
      "name_zh": "喀麦隆",
      "name_ru": "Камерун",
      "name_en": "Cameroon",
      "M49 Code": 120,
      "ISO-alpha2 Code": "CM",
      "ISO-alpha3 Code": "CMR",
      "name_pt": "Camarões"
    },
    {
      "name_es": "República Centroafricana",
      "name_ar": "جمهورية أفريقيا الوسطى",
      "name_fr": "République centrafricaine",
      "name_zh": "中非共和国",
      "name_ru": "Центральноафриканская Республика",
      "name_en": "Central African Republic",
      "M49 Code": 140,
      "ISO-alpha2 Code": "CF",
      "ISO-alpha3 Code": "CAF",
      "name_pt": "República Centro-Africana"
    },
    {
      "name_es": "Chad",
      "name_ar": "تشاد",
      "name_fr": "Tchad",
      "name_zh": "乍得",
      "name_ru": "Чад",
      "name_en": "Chad",
      "M49 Code": 148,
      "ISO-alpha2 Code": "TD",
      "ISO-alpha3 Code": "TCD",
      "name_pt": "Chade"
    },
    {
      "name_es": "Congo",
      "name_ar": "الكونغو",
      "name_fr": "Congo",
      "name_zh": "刚果",
      "name_ru": "Конго",
      "name_en": "Congo",
      "M49 Code": 178,
      "ISO-alpha2 Code": "CG",
      "ISO-alpha3 Code": "COG",
      "name_pt": "Congo"
    },
    {
      "name_es": "República Democrática del Congo",
      "name_ar": "جمهورية الكونغو الديمقراطية",
      "name_fr": "République démocratique du Congo",
      "name_zh": "刚果民主共和国",
      "name_ru": "Демократическая Республика Конго",
      "name_en": "Democratic Republic of the Congo",
      "M49 Code": 180,
      "ISO-alpha2 Code": "CD",
      "ISO-alpha3 Code": "COD",
      "name_pt": "República Democrática do Congo"
    },
    {
      "name_es": "Guinea Ecuatorial",
      "name_ar": "غينيا الاستوائية",
      "name_fr": "Guinée équatoriale",
      "name_zh": "赤道几内亚",
      "name_ru": "Экваториальная Гвинея",
      "name_en": "Equatorial Guinea",
      "M49 Code": 226,
      "ISO-alpha2 Code": "GQ",
      "ISO-alpha3 Code": "GNQ",
      "name_pt": "Guiné Equatorial"
    },
    {
      "name_es": "Gabón",
      "name_ar": "غابون",
      "name_fr": "Gabon",
      "name_zh": "加蓬",
      "name_ru": "Габон",
      "name_en": "Gabon",
      "M49 Code": 266,
      "ISO-alpha2 Code": "GA",
      "ISO-alpha3 Code": "GAB",
      "name_pt": "Gabão"
    },
    {
      "name_es": "Santo Tomé y Príncipe",
      "name_ar": "سان تومي وبرينسيبي",
      "name_fr": "Sao Tomé-et-Principe",
      "name_zh": "圣多美和普林西比",
      "name_ru": "Сан-Томе и Принсипи",
      "name_en": "Sao Tome and Principe",
      "M49 Code": 678,
      "ISO-alpha2 Code": "ST",
      "ISO-alpha3 Code": "STP",
      "name_pt": "São Tomé e Príncipe"
    },
    {
      "name_es": "Botswana",
      "name_ar": "بوتسوانا",
      "name_fr": "Botswana",
      "name_zh": "博茨瓦纳",
      "name_ru": "Ботсвана",
      "name_en": "Botswana",
      "M49 Code": 72,
      "ISO-alpha2 Code": "BW",
      "ISO-alpha3 Code": "BWA",
      "name_pt": "Botsuana"
    },
    {
      "name_es": "Eswatini",
      "name_ar": "إسواتيني",
      "name_fr": "Eswatini",
      "name_zh": "斯威士兰",
      "name_ru": "Эсватини",
      "name_en": "Eswatini",
      "M49 Code": 748,
      "ISO-alpha2 Code": "SZ",
      "ISO-alpha3 Code": "SWZ",
      "name_pt": "Essuatíni"
    },
    {
      "name_es": "Lesotho",
      "name_ar": "ليسوتو",
      "name_fr": "Lesotho",
      "name_zh": "莱索托",
      "name_ru": "Лесото",
      "name_en": "Lesotho",
      "M49 Code": 426,
      "ISO-alpha2 Code": "LS",
      "ISO-alpha3 Code": "LSO",
      "name_pt": "Lesoto"
    },
    {
      "name_es": "Namibia",
      "name_ar": "ناميبيا",
      "name_fr": "Namibie",
      "name_zh": "纳米比亚",
      "name_ru": "Намибия",
      "name_en": "Namibia",
      "M49 Code": 516,
      "ISO-alpha2 Code": "NA",
      "ISO-alpha3 Code": "NAM",
      "name_pt": "Namíbia"
    },
    {
      "name_es": "Sudáfrica",
      "name_ar": "جنوب أفريقيا",
      "name_fr": "Afrique du Sud",
      "name_zh": "南非",
      "name_ru": "Южная Африка",
      "name_en": "South Africa",
      "M49 Code": 710,
      "ISO-alpha2 Code": "ZA",
      "ISO-alpha3 Code": "ZAF",
      "name_pt": "África do Sul"
    },
    {
      "name_es": "Benin",
      "name_ar": "بنن",
      "name_fr": "Bénin",
      "name_zh": "贝宁",
      "name_ru": "Бенин",
      "name_en": "Benin",
      "M49 Code": 204,
      "ISO-alpha2 Code": "BJ",
      "ISO-alpha3 Code": "BEN",
      "name_pt": "Benim"
    },
    {
      "name_es": "Burkina Faso",
      "name_ar": "بوركينا فاسو",
      "name_fr": "Burkina Faso",
      "name_zh": "布基纳法索",
      "name_ru": "Буркина-Фасо",
      "name_en": "Burkina Faso",
      "M49 Code": 854,
      "ISO-alpha2 Code": "BF",
      "ISO-alpha3 Code": "BFA",
      "name_pt": "Burkina Faso"
    },
    {
      "name_es": "Cabo Verde",
      "name_ar": "كابو فيردي",
      "name_fr": "Cabo Verde",
      "name_zh": "佛得角",
      "name_ru": "Кабо-Верде",
      "name_en": "Cabo Verde",
      "M49 Code": 132,
      "ISO-alpha2 Code": "CV",
      "ISO-alpha3 Code": "CPV",
      "name_pt": "Cabo Verde"
    },
    {
      "name_es": "Côte d’Ivoire",
      "name_ar": "كوت ديفوار",
      "name_fr": "Côte d’Ivoire",
      "name_zh": "科特迪瓦",
      "name_ru": "Кот-д'Ивуар",
      "name_en": "Côte d’Ivoire",
      "M49 Code": 384,
      "ISO-alpha2 Code": "CI",
      "ISO-alpha3 Code": "CIV",
      "name_pt": "Costa do Marfim"
    },
    {
      "name_es": "Gambia",
      "name_ar": "غامبيا",
      "name_fr": "Gambie",
      "name_zh": "冈比亚",
      "name_ru": "Гамбия",
      "name_en": "Gambia",
      "M49 Code": 270,
      "ISO-alpha2 Code": "GM",
      "ISO-alpha3 Code": "GMB",
      "name_pt": "Gâmbia"
    },
    {
      "name_es": "Ghana",
      "name_ar": "غانا",
      "name_fr": "Ghana",
      "name_zh": "加纳",
      "name_ru": "Гана",
      "name_en": "Ghana",
      "M49 Code": 288,
      "ISO-alpha2 Code": "GH",
      "ISO-alpha3 Code": "GHA",
      "name_pt": "Gana"
    },
    {
      "name_es": "Guinea",
      "name_ar": "غينيا",
      "name_fr": "Guinée",
      "name_zh": "几内亚",
      "name_ru": "Гвинея",
      "name_en": "Guinea",
      "M49 Code": 324,
      "ISO-alpha2 Code": "GN",
      "ISO-alpha3 Code": "GIN",
      "name_pt": "Guiné"
    },
    {
      "name_es": "Guinea-Bissau",
      "name_ar": "غينيا - بيساو",
      "name_fr": "Guinée-Bissau",
      "name_zh": "几内亚比绍",
      "name_ru": "Гвинея-Бисау",
      "name_en": "Guinea-Bissau",
      "M49 Code": 624,
      "ISO-alpha2 Code": "GW",
      "ISO-alpha3 Code": "GNB",
      "name_pt": "Guiné-Bissau"
    },
    {
      "name_es": "Liberia",
      "name_ar": "ليبريا",
      "name_fr": "Libéria",
      "name_zh": "利比里亚",
      "name_ru": "Либерия",
      "name_en": "Liberia",
      "M49 Code": 430,
      "ISO-alpha2 Code": "LR",
      "ISO-alpha3 Code": "LBR",
      "name_pt": "Libéria"
    },
    {
      "name_es": "Malí",
      "name_ar": "مالي",
      "name_fr": "Mali",
      "name_zh": "马里",
      "name_ru": "Мали",
      "name_en": "Mali",
      "M49 Code": 466,
      "ISO-alpha2 Code": "ML",
      "ISO-alpha3 Code": "MLI",
      "name_pt": "Mali"
    },
    {
      "name_es": "Mauritania",
      "name_ar": "موريتانيا",
      "name_fr": "Mauritanie",
      "name_zh": "毛里塔尼亚",
      "name_ru": "Мавритания",
      "name_en": "Mauritania",
      "M49 Code": 478,
      "ISO-alpha2 Code": "MR",
      "ISO-alpha3 Code": "MRT",
      "name_pt": "Mauritânia"
    },
    {
      "name_es": "Níger",
      "name_ar": "النيجر",
      "name_fr": "Niger",
      "name_zh": "尼日尔",
      "name_ru": "Нигер",
      "name_en": "Niger",
      "M49 Code": 562,
      "ISO-alpha2 Code": "NE",
      "ISO-alpha3 Code": "NER",
      "name_pt": "Níger"
    },
    {
      "name_es": "Nigeria",
      "name_ar": "نيجيريا",
      "name_fr": "Nigéria",
      "name_zh": "尼日利亚",
      "name_ru": "Нигерия",
      "name_en": "Nigeria",
      "M49 Code": 566,
      "ISO-alpha2 Code": "NG",
      "ISO-alpha3 Code": "NGA",
      "name_pt": "Nigéria"
    },
    {
      "name_es": "Santa Elena",
      "name_ar": "سانت هيلانة",
      "name_fr": "Sainte-Hélène",
      "name_zh": "圣赫勒拿",
      "name_ru": "Остров Святой Елены",
      "name_en": "Saint Helena",
      "M49 Code": 654,
      "ISO-alpha2 Code": "SH",
      "ISO-alpha3 Code": "SHN",
      "name_pt": "Santa Helena"
    },
    {
      "name_es": "Senegal",
      "name_ar": "السنغال",
      "name_fr": "Sénégal",
      "name_zh": "塞内加尔",
      "name_ru": "Сенегал",
      "name_en": "Senegal",
      "M49 Code": 686,
      "ISO-alpha2 Code": "SN",
      "ISO-alpha3 Code": "SEN",
      "name_pt": "Senegal"
    },
    {
      "name_es": "Sierra Leona",
      "name_ar": "سيراليون",
      "name_fr": "Sierra Leone",
      "name_zh": "塞拉利昂",
      "name_ru": "Сьерра-Леоне",
      "name_en": "Sierra Leone",
      "M49 Code": 694,
      "ISO-alpha2 Code": "SL",
      "ISO-alpha3 Code": "SLE",
      "name_pt": "Serra Leoa"
    },
    {
      "name_es": "Togo",
      "name_ar": "توغو",
      "name_fr": "Togo",
      "name_zh": "多哥",
      "name_ru": "Того",
      "name_en": "Togo",
      "M49 Code": 768,
      "ISO-alpha2 Code": "TG",
      "ISO-alpha3 Code": "TGO",
      "name_pt": "Togo"
    },
    {
      "name_es": "Anguila",
      "name_ar": "أنغويلا",
      "name_fr": "Anguilla",
      "name_zh": "安圭拉",
      "name_ru": "Ангилья",
      "name_en": "Anguilla",
      "M49 Code": 660,
      "ISO-alpha2 Code": "AI",
      "ISO-alpha3 Code": "AIA",
      "name_pt": "Anguila"
    },
    {
      "name_es": "Antigua y Barbuda",
      "name_ar": "أنتيغوا وبربودا",
      "name_fr": "Antigua-et-Barbuda",
      "name_zh": "安提瓜和巴布达",
      "name_ru": "Антигуа и Барбуда",
      "name_en": "Antigua and Barbuda",
      "M49 Code": 28,
      "ISO-alpha2 Code": "AG",
      "ISO-alpha3 Code": "ATG",
      "name_pt": "Antígua e Barbuda"
    },
    {
      "name_es": "Aruba",
      "name_ar": "أروبا",
      "name_fr": "Aruba",
      "name_zh": "阿鲁巴",
      "name_ru": "Аруба",
      "name_en": "Aruba",
      "M49 Code": 533,
      "ISO-alpha2 Code": "AW",
      "ISO-alpha3 Code": "ABW",
      "name_pt": "Aruba"
    },
    {
      "name_es": "Bahamas",
      "name_ar": "جزر البهاما",
      "name_fr": "Bahamas",
      "name_zh": "巴哈马",
      "name_ru": "Багамские Острова",
      "name_en": "Bahamas",
      "M49 Code": 44,
      "ISO-alpha2 Code": "BS",
      "ISO-alpha3 Code": "BHS",
      "name_pt": "Bahamas"
    },
    {
      "name_es": "Barbados",
      "name_ar": "بربادوس",
      "name_fr": "Barbade",
      "name_zh": "巴巴多斯",
      "name_ru": "Барбадос",
      "name_en": "Barbados",
      "M49 Code": 52,
      "ISO-alpha2 Code": "BB",
      "ISO-alpha3 Code": "BRB",
      "name_pt": "Barbados"
    },
    {
      "name_es": "Bonaire, San Eustaquio y Saba",
      "name_ar": "بونير وسانت يوستاشيوس وسابا",
      "name_fr": "Bonaire, Saint-Eustache et Saba",
      "name_zh": "博纳尔，圣俄斯塔休斯和萨巴",
      "name_ru": "Бонайре, Синт-Эстатиус и Саба",
      "name_en": "Bonaire, Sint Eustatius and Saba",
      "M49 Code": 535,
      "ISO-alpha2 Code": "BQ",
      "ISO-alpha3 Code": "BES",
      "name_pt": "Bonaire, Santo Eustáquio e Saba"
    },
    {
      "name_es": "Islas Vírgenes Británicas",
      "name_ar": "جزر فرجن البريطانية",
      "name_fr": "Îles Vierges britanniques",
      "name_zh": "英属维尔京群岛",
      "name_ru": "Британские Виргинские острова",
      "name_en": "British Virgin Islands",
      "M49 Code": 92,
      "ISO-alpha2 Code": "VG",
      "ISO-alpha3 Code": "VGB",
      "name_pt": "Ilhas Virgens Britânicas"
    },
    {
      "name_es": "Islas Caimán",
      "name_ar": "جزر كايمان",
      "name_fr": "Îles Caïmanes",
      "name_zh": "开曼群岛",
      "name_ru": "Кайман острова",
      "name_en": "Cayman Islands",
      "M49 Code": 136,
      "ISO-alpha2 Code": "KY",
      "ISO-alpha3 Code": "CYM",
      "name_pt": "Ilhas Cayman"
    },
    {
      "name_es": "Cuba",
      "name_ar": "كوبا",
      "name_fr": "Cuba",
      "name_zh": "古巴",
      "name_ru": "Куба",
      "name_en": "Cuba",
      "M49 Code": 192,
      "ISO-alpha2 Code": "CU",
      "ISO-alpha3 Code": "CUB",
      "name_pt": "Cuba"
    },
    {
      "name_es": "Curazao",
      "name_ar": "كوراساو",
      "name_fr": "Curaçao",
      "name_zh": "库拉索",
      "name_ru": "Кюрасао",
      "name_en": "Curaçao",
      "M49 Code": 531,
      "ISO-alpha2 Code": "CW",
      "ISO-alpha3 Code": "CUW",
      "name_pt": "Curaçao"
    },
    {
      "name_es": "Dominica",
      "name_ar": "دومينيكا",
      "name_fr": "Dominique",
      "name_zh": "多米尼克",
      "name_ru": "Доминика",
      "name_en": "Dominica",
      "M49 Code": 212,
      "ISO-alpha2 Code": "DM",
      "ISO-alpha3 Code": "DMA",
      "name_pt": "Dominica"
    },
    {
      "name_es": "República Dominicana",
      "name_ar": "الجمهورية الدومينيكية",
      "name_fr": "République dominicaine",
      "name_zh": "多米尼加",
      "name_ru": "Доминиканская Республика",
      "name_en": "Dominican Republic",
      "M49 Code": 214,
      "ISO-alpha2 Code": "DO",
      "ISO-alpha3 Code": "DOM",
      "name_pt": "República Dominicana"
    },
    {
      "name_es": "Granada",
      "name_ar": "غرينادا",
      "name_fr": "Grenade",
      "name_zh": "格林纳达",
      "name_ru": "Гренада",
      "name_en": "Grenada",
      "M49 Code": 308,
      "ISO-alpha2 Code": "GD",
      "ISO-alpha3 Code": "GRD",
      "name_pt": "Granada"
    },
    {
      "name_es": "Guadalupe",
      "name_ar": "غوادلوب",
      "name_fr": "Guadeloupe",
      "name_zh": "瓜德罗普",
      "name_ru": "Гваделупа",
      "name_en": "Guadeloupe",
      "M49 Code": 312,
      "ISO-alpha2 Code": "GP",
      "ISO-alpha3 Code": "GLP",
      "name_pt": "Guadalupe"
    },
    {
      "name_es": "Haití",
      "name_ar": "هايتي",
      "name_fr": "Haïti",
      "name_zh": "海地",
      "name_ru": "Гаити",
      "name_en": "Haiti",
      "M49 Code": 332,
      "ISO-alpha2 Code": "HT",
      "ISO-alpha3 Code": "HTI",
      "name_pt": "Haiti"
    },
    {
      "name_es": "Jamaica",
      "name_ar": "جامايكا",
      "name_fr": "Jamaïque",
      "name_zh": "牙买加",
      "name_ru": "Ямайка",
      "name_en": "Jamaica",
      "M49 Code": 388,
      "ISO-alpha2 Code": "JM",
      "ISO-alpha3 Code": "JAM",
      "name_pt": "Jamaica"
    },
    {
      "name_es": "Martinica",
      "name_ar": "مارتينيك",
      "name_fr": "Martinique",
      "name_zh": "马提尼克",
      "name_ru": "Мартиника",
      "name_en": "Martinique",
      "M49 Code": 474,
      "ISO-alpha2 Code": "MQ",
      "ISO-alpha3 Code": "MTQ",
      "name_pt": "Martinica"
    },
    {
      "name_es": "Montserrat",
      "name_ar": "مونتسيرات",
      "name_fr": "Montserrat",
      "name_zh": "蒙特塞拉特",
      "name_ru": "Монтсеррат",
      "name_en": "Montserrat",
      "M49 Code": 500,
      "ISO-alpha2 Code": "MS",
      "ISO-alpha3 Code": "MSR",
      "name_pt": "Monserrate"
    },
    {
      "name_es": "Puerto Rico",
      "name_ar": "بورتوريكو",
      "name_fr": "Porto Rico",
      "name_zh": "波多黎各",
      "name_ru": "Пуэрто-Рико",
      "name_en": "Puerto Rico",
      "M49 Code": 630,
      "ISO-alpha2 Code": "PR",
      "ISO-alpha3 Code": "PRI",
      "name_pt": "Porto Rico"
    },
    {
      "name_es": "San Barthélemy",
      "name_ar": "سان بارتليمي",
      "name_fr": "Saint-Barthélemy",
      "name_zh": "圣巴泰勒米",
      "name_ru": "Сен-Бартелеми",
      "name_en": "Saint Barthélemy",
      "M49 Code": 652,
      "ISO-alpha2 Code": "BL",
      "ISO-alpha3 Code": "BLM",
      "name_pt": "São Bartolomeu"
    },
    {
      "name_es": "Saint Kitts y Nevis",
      "name_ar": "سانت كيتس ونيفس",
      "name_fr": "Saint-Kitts-et-Nevis",
      "name_zh": "圣基茨和尼维斯",
      "name_ru": "Сент-Китс и Невис",
      "name_en": "Saint Kitts and Nevis",
      "M49 Code": 659,
      "ISO-alpha2 Code": "KN",
      "ISO-alpha3 Code": "KNA",
      "name_pt": "São Cristóvão e Névis"
    },
    {
      "name_es": "Santa Lucía",
      "name_ar": "سانت لوسيا",
      "name_fr": "Sainte-Lucie",
      "name_zh": "圣卢西亚",
      "name_ru": "Сент-Люсия",
      "name_en": "Saint Lucia",
      "M49 Code": 662,
      "ISO-alpha2 Code": "LC",
      "ISO-alpha3 Code": "LCA",
      "name_pt": "Santa Lúcia"
    },
    {
      "name_es": "San Martín (parte francesa)",
      "name_ar": "سانت مارتن (الجزء الفرنسي)",
      "name_fr": "Saint-Martin (partie française)",
      "name_zh": "圣马丁（法属）",
      "name_ru": "Сен-Мартен (французская часть)",
      "name_en": "Saint Martin (French Part)",
      "M49 Code": 663,
      "ISO-alpha2 Code": "MF",
      "ISO-alpha3 Code": "MAF",
      "name_pt": "São Martinho (parte francesa)"
    },
    {
      "name_es": "San Vicente y las Granadinas",
      "name_ar": "سانت فنسنت وجزر غرينادين",
      "name_fr": "Saint-Vincent-et-les Grenadines",
      "name_zh": "圣文森特和格林纳丁斯",
      "name_ru": "Сент-Винсент и Гренадины",
      "name_en": "Saint Vincent and the Grenadines",
      "M49 Code": 670,
      "ISO-alpha2 Code": "VC",
      "ISO-alpha3 Code": "VCT",
      "name_pt": "São Vicente e Granadinas"
    },
    {
      "name_es": "San Martín (parte Holandesa)",
      "name_ar": "سانت مارتن (الجزء الهولندي)",
      "name_fr": "Saint-Martin (partie néerlandaise)",
      "name_zh": "圣马丁（荷属）",
      "name_ru": "Синт-Мартен (нидерландская часть)",
      "name_en": "Sint Maarten (Dutch part)",
      "M49 Code": 534,
      "ISO-alpha2 Code": "SX",
      "ISO-alpha3 Code": "SXM",
      "name_pt": "São Martinho (parte holandesa)"
    },
    {
      "name_es": "Trinidad y Tabago",
      "name_ar": "ترينيداد وتوباغو",
      "name_fr": "Trinité-et-Tobago",
      "name_zh": "特立尼达和多巴哥",
      "name_ru": "Тринидад и Тобаго",
      "name_en": "Trinidad and Tobago",
      "M49 Code": 780,
      "ISO-alpha2 Code": "TT",
      "ISO-alpha3 Code": "TTO",
      "name_pt": "Trindade e Tobago"
    },
    {
      "name_es": "Islas Turcas y Caicos",
      "name_ar": "جزر تركس وكايكوس",
      "name_fr": "Îles Turques-et-Caïques",
      "name_zh": "特克斯和凯科斯群岛",
      "name_ru": "Острова Теркс и Кайкос",
      "name_en": "Turks and Caicos Islands",
      "M49 Code": 796,
      "ISO-alpha2 Code": "TC",
      "ISO-alpha3 Code": "TCA",
      "name_pt": "Ilhas Turcas e Caicos"
    },
    {
      "name_es": "Islas Vírgenes de los Estados Unidos",
      "name_ar": "جزر فرجن التابعة للولايات المتحدة",
      "name_fr": "Îles Vierges américaines",
      "name_zh": "美属维尔京群岛",
      "name_ru": "Виргинские острова Соединенных Штатов",
      "name_en": "United States Virgin Islands",
      "M49 Code": 850,
      "ISO-alpha2 Code": "VI",
      "ISO-alpha3 Code": "VIR",
      "name_pt": "Ilhas Virgens dos Estados Unidos"
    },
    {
      "name_es": "Belice",
      "name_ar": "بليز",
      "name_fr": "Belize",
      "name_zh": "伯利兹",
      "name_ru": "Белиз",
      "name_en": "Belize",
      "M49 Code": 84,
      "ISO-alpha2 Code": "BZ",
      "ISO-alpha3 Code": "BLZ",
      "name_pt": "Belize"
    },
    {
      "name_es": "Costa Rica",
      "name_ar": "كوستاريكا",
      "name_fr": "Costa Rica",
      "name_zh": "哥斯达黎加",
      "name_ru": "Коста-Рика",
      "name_en": "Costa Rica",
      "M49 Code": 188,
      "ISO-alpha2 Code": "CR",
      "ISO-alpha3 Code": "CRI",
      "name_pt": "Costa Rica"
    },
    {
      "name_es": "El Salvador",
      "name_ar": "السلفادور",
      "name_fr": "El Salvador",
      "name_zh": "萨尔瓦多",
      "name_ru": "Сальвадор",
      "name_en": "El Salvador",
      "M49 Code": 222,
      "ISO-alpha2 Code": "SV",
      "ISO-alpha3 Code": "SLV",
      "name_pt": "El Salvador"
    },
    {
      "name_es": "Guatemala",
      "name_ar": "غواتيمالا",
      "name_fr": "Guatemala",
      "name_zh": "危地马拉",
      "name_ru": "Гватемала",
      "name_en": "Guatemala",
      "M49 Code": 320,
      "ISO-alpha2 Code": "GT",
      "ISO-alpha3 Code": "GTM",
      "name_pt": "Guatemala"
    },
    {
      "name_es": "Honduras",
      "name_ar": "هندوراس",
      "name_fr": "Honduras",
      "name_zh": "洪都拉斯",
      "name_ru": "Гондурас",
      "name_en": "Honduras",
      "M49 Code": 340,
      "ISO-alpha2 Code": "HN",
      "ISO-alpha3 Code": "HND",
      "name_pt": "Honduras"
    },
    {
      "name_es": "México",
      "name_ar": "المكسيك",
      "name_fr": "Mexique",
      "name_zh": "墨西哥",
      "name_ru": "Мексика",
      "name_en": "Mexico",
      "M49 Code": 484,
      "ISO-alpha2 Code": "MX",
      "ISO-alpha3 Code": "MEX",
      "name_pt": "México"
    },
    {
      "name_es": "Nicaragua",
      "name_ar": "نيكاراغوا",
      "name_fr": "Nicaragua",
      "name_zh": "尼加拉瓜",
      "name_ru": "Никарагуа",
      "name_en": "Nicaragua",
      "M49 Code": 558,
      "ISO-alpha2 Code": "NI",
      "ISO-alpha3 Code": "NIC",
      "name_pt": "Nicarágua"
    },
    {
      "name_es": "Panamá",
      "name_ar": "بنما",
      "name_fr": "Panama",
      "name_zh": "巴拿马",
      "name_ru": "Панама",
      "name_en": "Panama",
      "M49 Code": 591,
      "ISO-alpha2 Code": "PA",
      "ISO-alpha3 Code": "PAN",
      "name_pt": "Panamá"
    },
    {
      "name_es": "Argentina",
      "name_ar": "الأرجنتين",
      "name_fr": "Argentine",
      "name_zh": "阿根廷",
      "name_ru": "Аргентина",
      "name_en": "Argentina",
      "M49 Code": 32,
      "ISO-alpha2 Code": "AR",
      "ISO-alpha3 Code": "ARG",
      "name_pt": "Argentina"
    },
    {
      "name_es": "Bolivia (Estado Plurinacional de)",
      "name_ar": "بوليفيا (دولة - المتعددة القوميات)",
      "name_fr": "Bolivie (État plurinational de)",
      "name_zh": "多民族玻利维亚国",
      "name_ru": "Боливия (Многонациональное Государство)",
      "name_en": "Bolivia (Plurinational State of)",
      "M49 Code": 68,
      "ISO-alpha2 Code": "BO",
      "ISO-alpha3 Code": "BOL",
      "name_pt": "Bolívia (Estado Plurinacional da)"
    },
    {
      "name_es": "Isla Bouvet",
      "name_ar": "جزيرة بوفيت",
      "name_fr": "Île Bouvet",
      "name_zh": "布维岛",
      "name_ru": "Остров Буве",
      "name_en": "Bouvet Island",
      "M49 Code": 74,
      "ISO-alpha2 Code": "BV",
      "ISO-alpha3 Code": "BVT",
      "name_pt": "Ilha Bouvet"
    },
    {
      "name_es": "Brasil",
      "name_ar": "البرازيل",
      "name_fr": "Brésil",
      "name_zh": "巴西",
      "name_ru": "Бразилия",
      "name_en": "Brazil",
      "M49 Code": 76,
      "ISO-alpha2 Code": "BR",
      "ISO-alpha3 Code": "BRA",
      "name_pt": "Brasil"
    },
    {
      "name_es": "Chile",
      "name_ar": "شيلي",
      "name_fr": "Chili",
      "name_zh": "智利",
      "name_ru": "Чили",
      "name_en": "Chile",
      "M49 Code": 152,
      "ISO-alpha2 Code": "CL",
      "ISO-alpha3 Code": "CHL",
      "name_pt": "Chile"
    },
    {
      "name_es": "Colombia",
      "name_ar": "كولومبيا",
      "name_fr": "Colombie",
      "name_zh": "哥伦比亚",
      "name_ru": "Колумбия",
      "name_en": "Colombia",
      "M49 Code": 170,
      "ISO-alpha2 Code": "CO",
      "ISO-alpha3 Code": "COL",
      "name_pt": "Colômbia"
    },
    {
      "name_es": "Ecuador",
      "name_ar": "إكوادور",
      "name_fr": "Équateur",
      "name_zh": "厄瓜多尔",
      "name_ru": "Эквадор",
      "name_en": "Ecuador",
      "M49 Code": 218,
      "ISO-alpha2 Code": "EC",
      "ISO-alpha3 Code": "ECU",
      "name_pt": "Equador"
    },
    {
      "name_es": "Islas Malvinas (Falkland)",
      "name_ar": "جزر فوكلاند (مالفيناس)",
      "name_fr": "Îles Falkland (Malvinas)",
      "name_zh": "福克兰群岛（马尔维纳斯）",
      "name_ru": "Фолклендские (Мальвинские) острова",
      "name_en": "Falkland Islands (Malvinas)",
      "M49 Code": 238,
      "ISO-alpha2 Code": "FK",
      "ISO-alpha3 Code": "FLK",
      "name_pt": "Ilhas Malvinas (Falkland)"
    },
    {
      "name_es": "Guayana Francesa",
      "name_ar": "غيانا الفرنسية",
      "name_fr": "Guyane française",
      "name_zh": "法属圭亚那",
      "name_ru": "Французская Гвиана",
      "name_en": "French Guiana",
      "M49 Code": 254,
      "ISO-alpha2 Code": "GF",
      "ISO-alpha3 Code": "GUF",
      "name_pt": "Guiana Francesa"
    },
    {
      "name_es": "Guyana",
      "name_ar": "غيانا",
      "name_fr": "Guyana",
      "name_zh": "圭亚那",
      "name_ru": "Гайана",
      "name_en": "Guyana",
      "M49 Code": 328,
      "ISO-alpha2 Code": "GY",
      "ISO-alpha3 Code": "GUY",
      "name_pt": "Guiana"
    },
    {
      "name_es": "Paraguay",
      "name_ar": "باراغواي",
      "name_fr": "Paraguay",
      "name_zh": "巴拉圭",
      "name_ru": "Парагвай",
      "name_en": "Paraguay",
      "M49 Code": 600,
      "ISO-alpha2 Code": "PY",
      "ISO-alpha3 Code": "PRY",
      "name_pt": "Paraguai"
    },
    {
      "name_es": "Perú",
      "name_ar": "بيرو",
      "name_fr": "Pérou",
      "name_zh": "秘鲁",
      "name_ru": "Перу",
      "name_en": "Peru",
      "M49 Code": 604,
      "ISO-alpha2 Code": "PE",
      "ISO-alpha3 Code": "PER",
      "name_pt": "Peru"
    },
    {
      "name_es": "Georgia del Sur y las Islas Sandwich del Sur",
      "name_ar": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
      "name_fr": "Géorgie du Sud-et-les Îles Sandwich du Sud",
      "name_zh": "南乔治亚岛和南桑德韦奇岛",
      "name_ru": "Южная Джорджия и Южные Сандвичевы острова",
      "name_en": "South Georgia and the South Sandwich Islands",
      "M49 Code": 239,
      "ISO-alpha2 Code": "GS",
      "ISO-alpha3 Code": "SGS",
      "name_pt": "Geórgia do Sul e Ilhas Sandwich do Sul"
    },
    {
      "name_es": "Suriname",
      "name_ar": "سورينام",
      "name_fr": "Suriname",
      "name_zh": "苏里南",
      "name_ru": "Суринам",
      "name_en": "Suriname",
      "M49 Code": 740,
      "ISO-alpha2 Code": "SR",
      "ISO-alpha3 Code": "SUR",
      "name_pt": "Suriname"
    },
    {
      "name_es": "Uruguay",
      "name_ar": "أوروغواي",
      "name_fr": "Uruguay",
      "name_zh": "乌拉圭",
      "name_ru": "Уругвай",
      "name_en": "Uruguay",
      "M49 Code": 858,
      "ISO-alpha2 Code": "UY",
      "ISO-alpha3 Code": "URY",
      "name_pt": "Uruguai"
    },
    {
      "name_es": "Venezuela (República Bolivariana de)",
      "name_ar": "فنزويلا (جمهورية - البوليفارية)",
      "name_fr": "Venezuela (République bolivarienne du)",
      "name_zh": "委内瑞拉玻利瓦尔共和国",
      "name_ru": "Венесуэла (Боливарианская Республика)",
      "name_en": "Venezuela (Bolivarian Republic of)",
      "M49 Code": 862,
      "ISO-alpha2 Code": "VE",
      "ISO-alpha3 Code": "VEN",
      "name_pt": "Venezuela (República Bolivariana da)"
    },
    {
      "name_es": "Bermuda",
      "name_ar": "برمودا",
      "name_fr": "Bermudes",
      "name_zh": "百慕大",
      "name_ru": "Бермудские острова",
      "name_en": "Bermuda",
      "M49 Code": 60,
      "ISO-alpha2 Code": "BM",
      "ISO-alpha3 Code": "BMU",
      "name_pt": "Bermudas"
    },
    {
      "name_es": "Canadá",
      "name_ar": "كندا",
      "name_fr": "Canada",
      "name_zh": "加拿大",
      "name_ru": "Канада",
      "name_en": "Canada",
      "M49 Code": 124,
      "ISO-alpha2 Code": "CA",
      "ISO-alpha3 Code": "CAN",
      "name_pt": "Canadá"
    },
    {
      "name_es": "Groenlandia",
      "name_ar": "غرينلند",
      "name_fr": "Groenland",
      "name_zh": "格陵兰",
      "name_ru": "Гренландия",
      "name_en": "Greenland",
      "M49 Code": 304,
      "ISO-alpha2 Code": "GL",
      "ISO-alpha3 Code": "GRL",
      "name_pt": "Groenlândia"
    },
    {
      "name_es": "San Pedro y Miquelón",
      "name_ar": "سان بيير وميكلون",
      "name_fr": "Saint-Pierre-et-Miquelon",
      "name_zh": "圣皮埃尔和密克隆",
      "name_ru": "Сен-Пьер и Микелон",
      "name_en": "Saint Pierre and Miquelon",
      "M49 Code": 666,
      "ISO-alpha2 Code": "PM",
      "ISO-alpha3 Code": "SPM",
      "name_pt": "São Pedro e Miquelão"
    },
    {
      "name_es": "Estados Unidos de América",
      "name_ar": "الولايات المتحدة الأمريكية",
      "name_fr": "États-Unis d’Amérique",
      "name_zh": "美利坚合众国",
      "name_ru": "Соединенные Штаты Америки",
      "name_en": "United States of America",
      "M49 Code": 840,
      "ISO-alpha2 Code": "US",
      "ISO-alpha3 Code": "USA",
      "name_pt": "Estados Unidos da América"
    },
    {
      "name_es": "Antártida",
      "name_ar": "أنتاركتيكا",
      "name_fr": "Antarctique",
      "name_zh": "南极洲",
      "name_ru": "Антарктике",
      "name_en": "Antarctica",
      "M49 Code": 10,
      "ISO-alpha2 Code": "AQ",
      "ISO-alpha3 Code": "ATA",
      "name_pt": "Antártida"
    },
    {
      "name_es": "Kazajstán",
      "name_ar": "كازاخستان",
      "name_fr": "Kazakhstan",
      "name_zh": "哈萨克斯坦",
      "name_ru": "Казахстан",
      "name_en": "Kazakhstan",
      "M49 Code": 398,
      "ISO-alpha2 Code": "KZ",
      "ISO-alpha3 Code": "KAZ",
      "name_pt": "Cazaquistão"
    },
    {
      "name_es": "Kirguistán",
      "name_ar": "قيرغيزستان",
      "name_fr": "Kirghizistan",
      "name_zh": "吉尔吉斯斯坦",
      "name_ru": "Кыргызстан",
      "name_en": "Kyrgyzstan",
      "M49 Code": 417,
      "ISO-alpha2 Code": "KG",
      "ISO-alpha3 Code": "KGZ",
      "name_pt": "Quirguistão"
    },
    {
      "name_es": "Tayikistán",
      "name_ar": "طاجيكستان",
      "name_fr": "Tadjikistan",
      "name_zh": "塔吉克斯坦",
      "name_ru": "Таджикистан",
      "name_en": "Tajikistan",
      "M49 Code": 762,
      "ISO-alpha2 Code": "TJ",
      "ISO-alpha3 Code": "TJK",
      "name_pt": "Tajiquistão"
    },
    {
      "name_es": "Turkmenistán",
      "name_ar": "تركمانستان",
      "name_fr": "Turkménistan",
      "name_zh": "土库曼斯坦",
      "name_ru": "Туркменистан",
      "name_en": "Turkmenistan",
      "M49 Code": 795,
      "ISO-alpha2 Code": "TM",
      "ISO-alpha3 Code": "TKM",
      "name_pt": "Turcomenistão"
    },
    {
      "name_es": "Uzbekistán",
      "name_ar": "أوزبكستان",
      "name_fr": "Ouzbékistan",
      "name_zh": "乌兹别克斯坦",
      "name_ru": "Узбекистан",
      "name_en": "Uzbekistan",
      "M49 Code": 860,
      "ISO-alpha2 Code": "UZ",
      "ISO-alpha3 Code": "UZB",
      "name_pt": "Uzbequistão"
    },
    {
      "name_es": "China",
      "name_ar": "الصين",
      "name_fr": "Chine",
      "name_zh": "中国",
      "name_ru": "Китай",
      "name_en": "China",
      "M49 Code": 156,
      "ISO-alpha2 Code": "CN",
      "ISO-alpha3 Code": "CHN",
      "name_pt": "China"
    },
    {
      "name_es": "China, región administrativa especial de Hong Kong",
      "name_ar": "الصين، منطقة هونغ كونغ الإدارية الخاصة",
      "name_fr": "Chine, région administrative spéciale de Hong Kong",
      "name_zh": "中国香港特别行政区",
      "name_ru": "Китай, Специальный административный район Гонконг",
      "name_en": "China, Hong Kong Special Administrative Region",
      "M49 Code": 344,
      "ISO-alpha2 Code": "HK",
      "ISO-alpha3 Code": "HKG",
      "name_pt": "China, Região Administrativa Especial de Hong Kong"
    },
    {
      "name_es": "China, región administrativa especial de Macao",
      "name_ar": "الصين، منطقة ماكاو الإدارية الخاصة",
      "name_fr": "Chine, région administrative spéciale de Macao",
      "name_zh": "中国澳门特别行政区",
      "name_ru": "Китай, Специальный административный район Макао",
      "name_en": "China, Macao Special Administrative Region",
      "M49 Code": 446,
      "ISO-alpha2 Code": "MO",
      "ISO-alpha3 Code": "MAC",
      "name_pt": "China, Região Administrativa Especial de Macau"
    },
    {
      "name_es": "República Popular Democrática de Corea",
      "name_ar": "جمهورية كوريا الشعبية الديمقراطية",
      "name_fr": "République populaire démocratique de Corée",
      "name_zh": "朝鲜民主主义人民共和国",
      "name_ru": "Корейская Народно-Демократическая Республика",
      "name_en": "Democratic People's Republic of Korea",
      "M49 Code": 408,
      "ISO-alpha2 Code": "KP",
      "ISO-alpha3 Code": "PRK",
      "name_pt": "República Popular Democrática da Coreia"
    },
    {
      "name_es": "Japón",
      "name_ar": "اليابان",
      "name_fr": "Japon",
      "name_zh": "日本",
      "name_ru": "Япония",
      "name_en": "Japan",
      "M49 Code": 392,
      "ISO-alpha2 Code": "JP",
      "ISO-alpha3 Code": "JPN",
      "name_pt": "Japão"
    },
    {
      "name_es": "Mongolia",
      "name_ar": "منغوليا",
      "name_fr": "Mongolie",
      "name_zh": "蒙古",
      "name_ru": "Монголия",
      "name_en": "Mongolia",
      "M49 Code": 496,
      "ISO-alpha2 Code": "MN",
      "ISO-alpha3 Code": "MNG",
      "name_pt": "Mongólia"
    },
    {
      "name_es": "República de Corea",
      "name_ar": "جمهورية كوريا",
      "name_fr": "République de Corée",
      "name_zh": "大韩民国",
      "name_ru": "Республика Корея",
      "name_en": "Republic of Korea",
      "M49 Code": 410,
      "ISO-alpha2 Code": "KR",
      "ISO-alpha3 Code": "KOR",
      "name_pt": "República da Coreia"
    },
    {
      "name_es": "Brunei Darussalam",
      "name_ar": "بروني دار السلام",
      "name_fr": "Brunéi Darussalam",
      "name_zh": "文莱达鲁萨兰国",
      "name_ru": "Бруней-Даруссалам",
      "name_en": "Brunei Darussalam",
      "M49 Code": 96,
      "ISO-alpha2 Code": "BN",
      "ISO-alpha3 Code": "BRN",
      "name_pt": "Brunei Darussalam"
    },
    {
      "name_es": "Camboya",
      "name_ar": "كمبوديا",
      "name_fr": "Cambodge",
      "name_zh": "柬埔寨",
      "name_ru": "Камбоджа",
      "name_en": "Cambodia",
      "M49 Code": 116,
      "ISO-alpha2 Code": "KH",
      "ISO-alpha3 Code": "KHM",
      "name_pt": "Camboja"
    },
    {
      "name_es": "Indonesia",
      "name_ar": "إندونيسيا",
      "name_fr": "Indonésie",
      "name_zh": "印度尼西亚",
      "name_ru": "Индонезия",
      "name_en": "Indonesia",
      "M49 Code": 360,
      "ISO-alpha2 Code": "ID",
      "ISO-alpha3 Code": "IDN",
      "name_pt": "Indonésia"
    },
    {
      "name_es": "República Democrática Popular Lao",
      "name_ar": "جمهورية لاو الديمقراطية الشعبية",
      "name_fr": "République démocratique populaire lao",
      "name_zh": "老挝人民民主共和国",
      "name_ru": "Лаосская Народно-Демократическая Республика",
      "name_en": "Lao People's Democratic Republic",
      "M49 Code": 418,
      "ISO-alpha2 Code": "LA",
      "ISO-alpha3 Code": "LAO",
      "name_pt": "República Democrática Popular do Laos"
    },
    {
      "name_es": "Malasia",
      "name_ar": "ماليزيا",
      "name_fr": "Malaisie",
      "name_zh": "马来西亚",
      "name_ru": "Малайзия",
      "name_en": "Malaysia",
      "M49 Code": 458,
      "ISO-alpha2 Code": "MY",
      "ISO-alpha3 Code": "MYS",
      "name_pt": "Malásia"
    },
    {
      "name_es": "Myanmar",
      "name_ar": "ميانمار",
      "name_fr": "Myanmar",
      "name_zh": "缅甸",
      "name_ru": "Мьянма",
      "name_en": "Myanmar",
      "M49 Code": 104,
      "ISO-alpha2 Code": "MM",
      "ISO-alpha3 Code": "MMR",
      "name_pt": "Mianmar"
    },
    {
      "name_es": "Filipinas",
      "name_ar": "الفلبين",
      "name_fr": "Philippines",
      "name_zh": "菲律宾",
      "name_ru": "Филиппины",
      "name_en": "Philippines",
      "M49 Code": 608,
      "ISO-alpha2 Code": "PH",
      "ISO-alpha3 Code": "PHL",
      "name_pt": "Filipinas"
    },
    {
      "name_es": "Singapur",
      "name_ar": "سنغافورة",
      "name_fr": "Singapour",
      "name_zh": "新加坡",
      "name_ru": "Сингапур",
      "name_en": "Singapore",
      "M49 Code": 702,
      "ISO-alpha2 Code": "SG",
      "ISO-alpha3 Code": "SGP",
      "name_pt": "Singapura"
    },
    {
      "name_es": "Tailandia",
      "name_ar": "تايلند",
      "name_fr": "Thaïlande",
      "name_zh": "泰国",
      "name_ru": "Таиланд",
      "name_en": "Thailand",
      "M49 Code": 764,
      "ISO-alpha2 Code": "TH",
      "ISO-alpha3 Code": "THA",
      "name_pt": "Tailândia"
    },
    {
      "name_es": "Timor-Leste",
      "name_ar": "تيمور - ليشتي",
      "name_fr": "Timor-Leste",
      "name_zh": "东帝汶",
      "name_ru": "Тимор-Лешти",
      "name_en": "Timor-Leste",
      "M49 Code": 626,
      "ISO-alpha2 Code": "TL",
      "ISO-alpha3 Code": "TLS",
      "name_pt": "Timor-Leste"
    },
    {
      "name_es": "Viet Nam",
      "name_ar": "فييت نام",
      "name_fr": "Viet Nam",
      "name_zh": "越南",
      "name_ru": "Вьетнам",
      "name_en": "Viet Nam",
      "M49 Code": 704,
      "ISO-alpha2 Code": "VN",
      "ISO-alpha3 Code": "VNM",
      "name_pt": "Vietnã"
    },
    {
      "name_es": "Afganistán",
      "name_ar": "أفغانستان",
      "name_fr": "Afghanistan",
      "name_zh": "阿富汗",
      "name_ru": "Афганистан",
      "name_en": "Afghanistan",
      "M49 Code": 4,
      "ISO-alpha2 Code": "AF",
      "ISO-alpha3 Code": "AFG",
      "name_pt": "Afeganistão"
    },
    {
      "name_es": "Bangladesh",
      "name_ar": "بنغلاديش",
      "name_fr": "Bangladesh",
      "name_zh": "孟加拉国",
      "name_ru": "Бангладеш",
      "name_en": "Bangladesh",
      "M49 Code": 50,
      "ISO-alpha2 Code": "BD",
      "ISO-alpha3 Code": "BGD",
      "name_pt": "Bangladesh"
    },
    {
      "name_es": "Bhután",
      "name_ar": "بوتان",
      "name_fr": "Bhoutan",
      "name_zh": "不丹",
      "name_ru": "Бутан",
      "name_en": "Bhutan",
      "M49 Code": 64,
      "ISO-alpha2 Code": "BT",
      "ISO-alpha3 Code": "BTN",
      "name_pt": "Butão"
    },
    {
      "name_es": "India",
      "name_ar": "الهند",
      "name_fr": "Inde",
      "name_zh": "印度",
      "name_ru": "Индия",
      "name_en": "India",
      "M49 Code": 356,
      "ISO-alpha2 Code": "IN",
      "ISO-alpha3 Code": "IND",
      "name_pt": "Índia"
    },
    {
      "name_es": "Irán (República Islámica del)",
      "name_ar": "إيران (جمهورية - الإسلامية)",
      "name_fr": "Iran (République islamique d’)",
      "name_zh": "伊朗伊斯兰共和国",
      "name_ru": "Иран (Исламская Республика)",
      "name_en": "Iran (Islamic Republic of)",
      "M49 Code": 364,
      "ISO-alpha2 Code": "IR",
      "ISO-alpha3 Code": "IRN",
      "name_pt": "Irã (República Islâmica do)"
    },
    {
      "name_es": "Maldivas",
      "name_ar": "ملديف",
      "name_fr": "Maldives",
      "name_zh": "马尔代夫",
      "name_ru": "Мальдивские Острова",
      "name_en": "Maldives",
      "M49 Code": 462,
      "ISO-alpha2 Code": "MV",
      "ISO-alpha3 Code": "MDV",
      "name_pt": "Maldivas"
    },
    {
      "name_es": "Nepal",
      "name_ar": "نيبال",
      "name_fr": "Népal",
      "name_zh": "尼泊尔",
      "name_ru": "Непал",
      "name_en": "Nepal",
      "M49 Code": 524,
      "ISO-alpha2 Code": "NP",
      "ISO-alpha3 Code": "NPL",
      "name_pt": "Nepal"
    },
    {
      "name_es": "Pakistán",
      "name_ar": "باكستان",
      "name_fr": "Pakistan",
      "name_zh": "巴基斯坦",
      "name_ru": "Пакистан",
      "name_en": "Pakistan",
      "M49 Code": 586,
      "ISO-alpha2 Code": "PK",
      "ISO-alpha3 Code": "PAK",
      "name_pt": "Paquistão"
    },
    {
      "name_es": "Sri Lanka",
      "name_ar": "سري لانكا",
      "name_fr": "Sri Lanka",
      "name_zh": "斯里兰卡",
      "name_ru": "Шри-Ланка",
      "name_en": "Sri Lanka",
      "M49 Code": 144,
      "ISO-alpha2 Code": "LK",
      "ISO-alpha3 Code": "LKA",
      "name_pt": "Sri Lanka"
    },
    {
      "name_es": "Armenia",
      "name_ar": "أرمينيا",
      "name_fr": "Arménie",
      "name_zh": "亚美尼亚",
      "name_ru": "Армения",
      "name_en": "Armenia",
      "M49 Code": 51,
      "ISO-alpha2 Code": "AM",
      "ISO-alpha3 Code": "ARM",
      "name_pt": "Armênia"
    },
    {
      "name_es": "Azerbaiyán",
      "name_ar": "أذربيجان",
      "name_fr": "Azerbaïdjan",
      "name_zh": "阿塞拜疆",
      "name_ru": "Азербайджан",
      "name_en": "Azerbaijan",
      "M49 Code": 31,
      "ISO-alpha2 Code": "AZ",
      "ISO-alpha3 Code": "AZE",
      "name_pt": "Azerbaijão"
    },
    {
      "name_es": "Bahrein",
      "name_ar": "البحرين",
      "name_fr": "Bahreïn",
      "name_zh": "巴林",
      "name_ru": "Бахрейн",
      "name_en": "Bahrain",
      "M49 Code": 48,
      "ISO-alpha2 Code": "BH",
      "ISO-alpha3 Code": "BHR",
      "name_pt": "Bahrein"
    },
    {
      "name_es": "Chipre",
      "name_ar": "قبرص",
      "name_fr": "Chypre",
      "name_zh": "塞浦路斯",
      "name_ru": "Кипр",
      "name_en": "Cyprus",
      "M49 Code": 196,
      "ISO-alpha2 Code": "CY",
      "ISO-alpha3 Code": "CYP",
      "name_pt": "Chipre"
    },
    {
      "name_es": "Georgia",
      "name_ar": "جورجيا",
      "name_fr": "Géorgie",
      "name_zh": "格鲁吉亚",
      "name_ru": "Грузия",
      "name_en": "Georgia",
      "M49 Code": 268,
      "ISO-alpha2 Code": "GE",
      "ISO-alpha3 Code": "GEO",
      "name_pt": "Geórgia"
    },
    {
      "name_es": "Iraq",
      "name_ar": "العراق",
      "name_fr": "Iraq",
      "name_zh": "伊拉克",
      "name_ru": "Ирак",
      "name_en": "Iraq",
      "M49 Code": 368,
      "ISO-alpha2 Code": "IQ",
      "ISO-alpha3 Code": "IRQ",
      "name_pt": "Iraque"
    },
    {
      "name_es": "Israel",
      "name_ar": "إسرائيل",
      "name_fr": "Israël",
      "name_zh": "以色列",
      "name_ru": "Израиль",
      "name_en": "Israel",
      "M49 Code": 376,
      "ISO-alpha2 Code": "IL",
      "ISO-alpha3 Code": "ISR",
      "name_pt": "Israel"
    },
    {
      "name_es": "Jordania",
      "name_ar": "الأردن",
      "name_fr": "Jordanie",
      "name_zh": "约旦",
      "name_ru": "Иордания",
      "name_en": "Jordan",
      "M49 Code": 400,
      "ISO-alpha2 Code": "JO",
      "ISO-alpha3 Code": "JOR",
      "name_pt": "Jordânia"
    },
    {
      "name_es": "Kuwait",
      "name_ar": "الكويت",
      "name_fr": "Koweït",
      "name_zh": "科威特",
      "name_ru": "Кувейт",
      "name_en": "Kuwait",
      "M49 Code": 414,
      "ISO-alpha2 Code": "KW",
      "ISO-alpha3 Code": "KWT",
      "name_pt": "Kuwait"
    },
    {
      "name_es": "Líbano",
      "name_ar": "لبنان",
      "name_fr": "Liban",
      "name_zh": "黎巴嫩",
      "name_ru": "Ливан",
      "name_en": "Lebanon",
      "M49 Code": 422,
      "ISO-alpha2 Code": "LB",
      "ISO-alpha3 Code": "LBN",
      "name_pt": "Líbano"
    },
    {
      "name_es": "Omán",
      "name_ar": "عمان",
      "name_fr": "Oman",
      "name_zh": "阿曼",
      "name_ru": "Оман",
      "name_en": "Oman",
      "M49 Code": 512,
      "ISO-alpha2 Code": "OM",
      "ISO-alpha3 Code": "OMN",
      "name_pt": "Omã"
    },
    {
      "name_es": "Qatar",
      "name_ar": "قطر",
      "name_fr": "Qatar",
      "name_zh": "卡塔尔",
      "name_ru": "Катар",
      "name_en": "Qatar",
      "M49 Code": 634,
      "ISO-alpha2 Code": "QA",
      "ISO-alpha3 Code": "QAT",
      "name_pt": "Catar"
    },
    {
      "name_es": "Arabia Saudita",
      "name_ar": "المملكة العربية السعودية",
      "name_fr": "Arabie saoudite",
      "name_zh": "沙特阿拉伯",
      "name_ru": "Саудовская Аравия",
      "name_en": "Saudi Arabia",
      "M49 Code": 682,
      "ISO-alpha2 Code": "SA",
      "ISO-alpha3 Code": "SAU",
      "name_pt": "Arábia Saudita"
    },
    {
      "name_es": "Estado de Palestina",
      "name_ar": "دولة فلسطين",
      "name_fr": "État de Palestine",
      "name_zh": "巴勒斯坦国",
      "name_ru": "Государство Палестина",
      "name_en": "State of Palestine",
      "M49 Code": 275,
      "ISO-alpha2 Code": "PS",
      "ISO-alpha3 Code": "PSE",
      "name_pt": "Estado da Palestina"
    },
    {
      "name_es": "República Árabe Siria",
      "name_ar": "الجمهورية العربية السورية",
      "name_fr": "République arabe syrienne",
      "name_zh": "阿拉伯叙利亚共和国",
      "name_ru": "Сирийская Арабская Республика",
      "name_en": "Syrian Arab Republic",
      "M49 Code": 760,
      "ISO-alpha2 Code": "SY",
      "ISO-alpha3 Code": "SYR",
      "name_pt": "República Árabe Síria"
    },
    {
      "name_es": "Türkiye",
      "name_ar": "تركيا",
      "name_fr": "Türkiye",
      "name_zh": "土耳其",
      "name_ru": "Турция",
      "name_en": "Türkiye",
      "M49 Code": 792,
      "ISO-alpha2 Code": "TR",
      "ISO-alpha3 Code": "TUR",
      "name_pt": "Turquia"
    },
    {
      "name_es": "Emiratos Árabes Unidos",
      "name_ar": "الإمارات العربية المتحدة",
      "name_fr": "Émirats arabes unis",
      "name_zh": "阿拉伯联合酋长国",
      "name_ru": "Объединенные Арабские Эмираты",
      "name_en": "United Arab Emirates",
      "M49 Code": 784,
      "ISO-alpha2 Code": "AE",
      "ISO-alpha3 Code": "ARE",
      "name_pt": "Emirados Árabes Unidos"
    },
    {
      "name_es": "Yemen",
      "name_ar": "اليمن",
      "name_fr": "Yémen",
      "name_zh": "也门",
      "name_ru": "Йемен",
      "name_en": "Yemen",
      "M49 Code": 887,
      "ISO-alpha2 Code": "YE",
      "ISO-alpha3 Code": "YEM",
      "name_pt": "Iêmen"
    },
    {
      "name_es": "Belarús",
      "name_ar": "بيلاروس",
      "name_fr": "Bélarus",
      "name_zh": "白俄罗斯",
      "name_ru": "Беларусь",
      "name_en": "Belarus",
      "M49 Code": 112,
      "ISO-alpha2 Code": "BY",
      "ISO-alpha3 Code": "BLR",
      "name_pt": "Bielorrússia"
    },
    {
      "name_es": "Bulgaria",
      "name_ar": "بلغاريا",
      "name_fr": "Bulgarie",
      "name_zh": "保加利亚",
      "name_ru": "Болгария",
      "name_en": "Bulgaria",
      "M49 Code": 100,
      "ISO-alpha2 Code": "BG",
      "ISO-alpha3 Code": "BGR",
      "name_pt": "Bulgária"
    },
    {
      "name_es": "Chequia",
      "name_ar": "تشيكيا",
      "name_fr": "Tchéquie",
      "name_zh": "捷克",
      "name_ru": "Чехия",
      "name_en": "Czechia",
      "M49 Code": 203,
      "ISO-alpha2 Code": "CZ",
      "ISO-alpha3 Code": "CZE",
      "name_pt": "Chéquia"
    },
    {
      "name_es": "Hungría",
      "name_ar": "هنغاريا",
      "name_fr": "Hongrie",
      "name_zh": "匈牙利",
      "name_ru": "Венгрия",
      "name_en": "Hungary",
      "M49 Code": 348,
      "ISO-alpha2 Code": "HU",
      "ISO-alpha3 Code": "HUN",
      "name_pt": "Hungria"
    },
    {
      "name_es": "Polonia",
      "name_ar": "بولندا",
      "name_fr": "Pologne",
      "name_zh": "波兰",
      "name_ru": "Польша",
      "name_en": "Poland",
      "M49 Code": 616,
      "ISO-alpha2 Code": "PL",
      "ISO-alpha3 Code": "POL",
      "name_pt": "Polônia"
    },
    {
      "name_es": "República de Moldova",
      "name_ar": "جمهورية مولدوفا",
      "name_fr": "République de Moldova",
      "name_zh": "摩尔多瓦共和国",
      "name_ru": "Республика Молдова",
      "name_en": "Republic of Moldova",
      "M49 Code": 498,
      "ISO-alpha2 Code": "MD",
      "ISO-alpha3 Code": "MDA",
      "name_pt": "República da Moldávia"
    },
    {
      "name_es": "Rumania",
      "name_ar": "رومانيا",
      "name_fr": "Roumanie",
      "name_zh": "罗马尼亚",
      "name_ru": "Румыния",
      "name_en": "Romania",
      "M49 Code": 642,
      "ISO-alpha2 Code": "RO",
      "ISO-alpha3 Code": "ROU",
      "name_pt": "Romênia"
    },
    {
      "name_es": "Federación de Rusia",
      "name_ar": "الاتحاد الروسي",
      "name_fr": "Fédération de Russie",
      "name_zh": "俄罗斯联邦",
      "name_ru": "Российская Федерация",
      "name_en": "Russian Federation",
      "M49 Code": 643,
      "ISO-alpha2 Code": "RU",
      "ISO-alpha3 Code": "RUS",
      "name_pt": "Federação Russa"
    },
    {
      "name_es": "Eslovaquia",
      "name_ar": "سلوفاكيا",
      "name_fr": "Slovaquie",
      "name_zh": "斯洛伐克",
      "name_ru": "Словакия",
      "name_en": "Slovakia",
      "M49 Code": 703,
      "ISO-alpha2 Code": "SK",
      "ISO-alpha3 Code": "SVK",
      "name_pt": "Eslováquia"
    },
    {
      "name_es": "Ucrania",
      "name_ar": "أوكرانيا",
      "name_fr": "Ukraine",
      "name_zh": "乌克兰",
      "name_ru": "Украина",
      "name_en": "Ukraine",
      "M49 Code": 804,
      "ISO-alpha2 Code": "UA",
      "ISO-alpha3 Code": "UKR",
      "name_pt": "Ucrânia"
    },
    {
      "name_es": "Islas Åland",
      "name_ar": "جزر ألاند",
      "name_fr": "Îles d’Åland",
      "name_zh": "奥兰群岛",
      "name_ru": "Аландских островов",
      "name_en": "Åland Islands",
      "M49 Code": 248,
      "ISO-alpha2 Code": "AX",
      "ISO-alpha3 Code": "ALA",
      "name_pt": "Ilhas Åland"
    },
    {
      "name_es": "Dinamarca",
      "name_ar": "الدانمرك",
      "name_fr": "Danemark",
      "name_zh": "丹麦",
      "name_ru": "Дания",
      "name_en": "Denmark",
      "M49 Code": 208,
      "ISO-alpha2 Code": "DK",
      "ISO-alpha3 Code": "DNK",
      "name_pt": "Dinamarca"
    },
    {
      "name_es": "Estonia",
      "name_ar": "إستونيا",
      "name_fr": "Estonie",
      "name_zh": "爱沙尼亚",
      "name_ru": "Эстония",
      "name_en": "Estonia",
      "M49 Code": 233,
      "ISO-alpha2 Code": "EE",
      "ISO-alpha3 Code": "EST",
      "name_pt": "Estônia"
    },
    {
      "name_es": "Islas Feroe",
      "name_ar": "جزر فايرو",
      "name_fr": "Îles Féroé",
      "name_zh": "法罗群岛",
      "name_ru": "Фарерские острова",
      "name_en": "Faroe Islands",
      "M49 Code": 234,
      "ISO-alpha2 Code": "FO",
      "ISO-alpha3 Code": "FRO",
      "name_pt": "Ilhas Feroé"
    },
    {
      "name_es": "Finlandia",
      "name_ar": "فنلندا",
      "name_fr": "Finlande",
      "name_zh": "芬兰",
      "name_ru": "Финляндия",
      "name_en": "Finland",
      "M49 Code": 246,
      "ISO-alpha2 Code": "FI",
      "ISO-alpha3 Code": "FIN",
      "name_pt": "Finlândia"
    },
    {
      "name_es": "Guernsey",
      "name_ar": "غيرنسي",
      "name_fr": "Guernesey",
      "name_zh": "格恩西",
      "name_ru": "Гернси",
      "name_en": "Guernsey",
      "M49 Code": 831,
      "ISO-alpha2 Code": "GG",
      "ISO-alpha3 Code": "GGY",
      "name_pt": "Guernsey"
    },
    {
      "name_es": "Islandia",
      "name_ar": "آيسلندا",
      "name_fr": "Islande",
      "name_zh": "冰岛",
      "name_ru": "Исландия",
      "name_en": "Iceland",
      "M49 Code": 352,
      "ISO-alpha2 Code": "IS",
      "ISO-alpha3 Code": "ISL",
      "name_pt": "Islândia"
    },
    {
      "name_es": "Irlanda",
      "name_ar": "آيرلندا",
      "name_fr": "Irlande",
      "name_zh": "爱尔兰",
      "name_ru": "Ирландия",
      "name_en": "Ireland",
      "M49 Code": 372,
      "ISO-alpha2 Code": "IE",
      "ISO-alpha3 Code": "IRL",
      "name_pt": "Irlanda"
    },
    {
      "name_es": "Isla de Man",
      "name_ar": "جزيرة مان",
      "name_fr": "Île de Man",
      "name_zh": "马恩岛",
      "name_ru": "Остров Мэн",
      "name_en": "Isle of Man",
      "M49 Code": 833,
      "ISO-alpha2 Code": "IM",
      "ISO-alpha3 Code": "IMN",
      "name_pt": "Ilha de Man"
    },
    {
      "name_es": "Jersey",
      "name_ar": "جيرسي",
      "name_fr": "Jersey",
      "name_zh": "泽西",
      "name_ru": "Джерси",
      "name_en": "Jersey",
      "M49 Code": 832,
      "ISO-alpha2 Code": "JE",
      "ISO-alpha3 Code": "JEY",
      "name_pt": "Jersey"
    },
    {
      "name_es": "Letonia",
      "name_ar": "لاتفيا",
      "name_fr": "Lettonie",
      "name_zh": "拉脱维亚",
      "name_ru": "Латвия",
      "name_en": "Latvia",
      "M49 Code": 428,
      "ISO-alpha2 Code": "LV",
      "ISO-alpha3 Code": "LVA",
      "name_pt": "Letônia"
    },
    {
      "name_es": "Lituania",
      "name_ar": "ليتوانيا",
      "name_fr": "Lituanie",
      "name_zh": "立陶宛",
      "name_ru": "Литва",
      "name_en": "Lithuania",
      "M49 Code": 440,
      "ISO-alpha2 Code": "LT",
      "ISO-alpha3 Code": "LTU",
      "name_pt": "Lituânia"
    },
    {
      "name_es": "Noruega",
      "name_ar": "النرويج",
      "name_fr": "Norvège",
      "name_zh": "挪威",
      "name_ru": "Норвегия",
      "name_en": "Norway",
      "M49 Code": 578,
      "ISO-alpha2 Code": "NO",
      "ISO-alpha3 Code": "NOR",
      "name_pt": "Noruega"
    },
    {
      "name_es": "Islas Svalbard y Jan Mayen",
      "name_ar": "جزيرتي سفالبارد وجان مايِن",
      "name_fr": "Îles Svalbard-et-Jan Mayen",
      "name_zh": "斯瓦尔巴群岛和扬马延岛",
      "name_ru": "Острова Свальбард и Ян-Майен",
      "name_en": "Svalbard and Jan Mayen Islands",
      "M49 Code": 744,
      "ISO-alpha2 Code": "SJ",
      "ISO-alpha3 Code": "SJM",
      "name_pt": "Ilhas Svalbard e Jan Mayen"
    },
    {
      "name_es": "Suecia",
      "name_ar": "السويد",
      "name_fr": "Suède",
      "name_zh": "瑞典",
      "name_ru": "Швеция",
      "name_en": "Sweden",
      "M49 Code": 752,
      "ISO-alpha2 Code": "SE",
      "ISO-alpha3 Code": "SWE",
      "name_pt": "Suécia"
    },
    {
      "name_es": "Reino Unido de Gran Bretaña e Irlanda del Norte",
      "name_ar": "المملكة المتحدة لبريطانيا العظمى وآيرلندا الشمالية",
      "name_fr": "Royaume-Uni de Grande-Bretagne et d’Irlande du Nord",
      "name_zh": "大不列颠及北爱尔兰联合王国",
      "name_ru": "Соединенное Королевство Великобритании и Северной Ирландии",
      "name_en": "United Kingdom of Great Britain and Northern Ireland",
      "M49 Code": 826,
      "ISO-alpha2 Code": "GB",
      "ISO-alpha3 Code": "GBR",
      "name_pt": "Reino Unido da Grã-Bretanha e Irlanda do Norte"
    },
    {
      "name_es": "Albania",
      "name_ar": "ألبانيا",
      "name_fr": "Albanie",
      "name_zh": "阿尔巴尼亚",
      "name_ru": "Албания",
      "name_en": "Albania",
      "M49 Code": 8,
      "ISO-alpha2 Code": "AL",
      "ISO-alpha3 Code": "ALB",
      "name_pt": "Albânia"
    },
    {
      "name_es": "Andorra",
      "name_ar": "أندورا",
      "name_fr": "Andorre",
      "name_zh": "安道尔",
      "name_ru": "Андорра",
      "name_en": "Andorra",
      "M49 Code": 20,
      "ISO-alpha2 Code": "AD",
      "ISO-alpha3 Code": "AND",
      "name_pt": "Andorra"
    },
    {
      "name_es": "Bosnia y Herzegovina",
      "name_ar": "البوسنة والهرسك",
      "name_fr": "Bosnie-Herzégovine",
      "name_zh": "波斯尼亚和黑塞哥维那",
      "name_ru": "Босния и Герцеговина",
      "name_en": "Bosnia and Herzegovina",
      "M49 Code": 70,
      "ISO-alpha2 Code": "BA",
      "ISO-alpha3 Code": "BIH",
      "name_pt": "Bósnia e Herzegovina"
    },
    {
      "name_es": "Croacia",
      "name_ar": "كرواتيا",
      "name_fr": "Croatie",
      "name_zh": "克罗地亚",
      "name_ru": "Хорватия",
      "name_en": "Croatia",
      "M49 Code": 191,
      "ISO-alpha2 Code": "HR",
      "ISO-alpha3 Code": "HRV",
      "name_pt": "Croácia"
    },
    {
      "name_es": "Gibraltar",
      "name_ar": "جبل طارق",
      "name_fr": "Gibraltar",
      "name_zh": "直布罗陀",
      "name_ru": "Гибралтар",
      "name_en": "Gibraltar",
      "M49 Code": 292,
      "ISO-alpha2 Code": "GI",
      "ISO-alpha3 Code": "GIB",
      "name_pt": "Gibraltar"
    },
    {
      "name_es": "Grecia",
      "name_ar": "اليونان",
      "name_fr": "Grèce",
      "name_zh": "希腊",
      "name_ru": "Греция",
      "name_en": "Greece",
      "M49 Code": 300,
      "ISO-alpha2 Code": "GR",
      "ISO-alpha3 Code": "GRC",
      "name_pt": "Grécia"
    },
    {
      "name_es": "Santa Sede",
      "name_ar": "الكرسي الرسولي",
      "name_fr": "Saint-Siège",
      "name_zh": "教廷",
      "name_ru": "Святой Престол",
      "name_en": "Holy See",
      "M49 Code": 336,
      "ISO-alpha2 Code": "VA",
      "ISO-alpha3 Code": "VAT",
      "name_pt": "Santa Sé"
    },
    {
      "name_es": "Italia",
      "name_ar": "إيطاليا",
      "name_fr": "Italie",
      "name_zh": "意大利",
      "name_ru": "Италия",
      "name_en": "Italy",
      "M49 Code": 380,
      "ISO-alpha2 Code": "IT",
      "ISO-alpha3 Code": "ITA",
      "name_pt": "Itália"
    },
    {
      "name_es": "Malta",
      "name_ar": "مالطة",
      "name_fr": "Malte",
      "name_zh": "马耳他",
      "name_ru": "Мальта",
      "name_en": "Malta",
      "M49 Code": 470,
      "ISO-alpha2 Code": "MT",
      "ISO-alpha3 Code": "MLT",
      "name_pt": "Malta"
    },
    {
      "name_es": "Montenegro",
      "name_ar": "الجبل الأسود",
      "name_fr": "Monténégro",
      "name_zh": "黑山",
      "name_ru": "Черногория",
      "name_en": "Montenegro",
      "M49 Code": 499,
      "ISO-alpha2 Code": "ME",
      "ISO-alpha3 Code": "MNE",
      "name_pt": "Montenegro"
    },
    {
      "name_es": "Macedonia del Norte",
      "name_ar": "مقدونيا الشمالية",
      "name_fr": "Macédoine du Nord",
      "name_zh": "北马其顿",
      "name_ru": "Северная Македония",
      "name_en": "North Macedonia",
      "M49 Code": 807,
      "ISO-alpha2 Code": "MK",
      "ISO-alpha3 Code": "MKD",
      "name_pt": "Macedônia do Norte"
    },
    {
      "name_es": "Portugal",
      "name_ar": "البرتغال",
      "name_fr": "Portugal",
      "name_zh": "葡萄牙",
      "name_ru": "Португалия",
      "name_en": "Portugal",
      "M49 Code": 620,
      "ISO-alpha2 Code": "PT",
      "ISO-alpha3 Code": "PRT",
      "name_pt": "Portugal"
    },
    {
      "name_es": "San Marino",
      "name_ar": "سان مارينو",
      "name_fr": "Saint-Marin",
      "name_zh": "圣马力诺",
      "name_ru": "Сан-Марино",
      "name_en": "San Marino",
      "M49 Code": 674,
      "ISO-alpha2 Code": "SM",
      "ISO-alpha3 Code": "SMR",
      "name_pt": "San Marino"
    },
    {
      "name_es": "Serbia",
      "name_ar": "صربيا",
      "name_fr": "Serbie",
      "name_zh": "塞尔维亚",
      "name_ru": "Сербия",
      "name_en": "Serbia",
      "M49 Code": 688,
      "ISO-alpha2 Code": "RS",
      "ISO-alpha3 Code": "SRB",
      "name_pt": "Sérvia"
    },
    {
      "name_es": "Eslovenia",
      "name_ar": "سلوفينيا",
      "name_fr": "Slovénie",
      "name_zh": "斯洛文尼亚",
      "name_ru": "Словения",
      "name_en": "Slovenia",
      "M49 Code": 705,
      "ISO-alpha2 Code": "SI",
      "ISO-alpha3 Code": "SVN",
      "name_pt": "Eslovênia"
    },
    {
      "name_es": "España",
      "name_ar": "إسبانيا",
      "name_fr": "Espagne",
      "name_zh": "西班牙",
      "name_ru": "Испания",
      "name_en": "Spain",
      "M49 Code": 724,
      "ISO-alpha2 Code": "ES",
      "ISO-alpha3 Code": "ESP",
      "name_pt": "Espanha"
    },
    {
      "name_es": "Austria",
      "name_ar": "النمسا",
      "name_fr": "Autriche",
      "name_zh": "奥地利",
      "name_ru": "Австрия",
      "name_en": "Austria",
      "M49 Code": 40,
      "ISO-alpha2 Code": "AT",
      "ISO-alpha3 Code": "AUT",
      "name_pt": "Áustria"
    },
    {
      "name_es": "Bélgica",
      "name_ar": "بلجيكا",
      "name_fr": "Belgique",
      "name_zh": "比利时",
      "name_ru": "Бельгия",
      "name_en": "Belgium",
      "M49 Code": 56,
      "ISO-alpha2 Code": "BE",
      "ISO-alpha3 Code": "BEL",
      "name_pt": "Bélgica"
    },
    {
      "name_es": "Francia",
      "name_ar": "فرنسا",
      "name_fr": "France",
      "name_zh": "法国",
      "name_ru": "Франция",
      "name_en": "France",
      "M49 Code": 250,
      "ISO-alpha2 Code": "FR",
      "ISO-alpha3 Code": "FRA",
      "name_pt": "França"
    },
    {
      "name_es": "Alemania",
      "name_ar": "ألمانيا",
      "name_fr": "Allemagne",
      "name_zh": "德国",
      "name_ru": "Германия",
      "name_en": "Germany",
      "M49 Code": 276,
      "ISO-alpha2 Code": "DE",
      "ISO-alpha3 Code": "DEU",
      "name_pt": "Alemanha"
    },
    {
      "name_es": "Liechtenstein",
      "name_ar": "ليختنشتاين",
      "name_fr": "Liechtenstein",
      "name_zh": "列支敦士登",
      "name_ru": "Лихтенштейн",
      "name_en": "Liechtenstein",
      "M49 Code": 438,
      "ISO-alpha2 Code": "LI",
      "ISO-alpha3 Code": "LIE",
      "name_pt": "Liechtenstein"
    },
    {
      "name_es": "Luxemburgo",
      "name_ar": "لكسمبرغ",
      "name_fr": "Luxembourg",
      "name_zh": "卢森堡",
      "name_ru": "Люксембург",
      "name_en": "Luxembourg",
      "M49 Code": 442,
      "ISO-alpha2 Code": "LU",
      "ISO-alpha3 Code": "LUX",
      "name_pt": "Luxemburgo"
    },
    {
      "name_es": "Mónaco",
      "name_ar": "موناكو",
      "name_fr": "Monaco",
      "name_zh": "摩纳哥",
      "name_ru": "Монако",
      "name_en": "Monaco",
      "M49 Code": 492,
      "ISO-alpha2 Code": "MC",
      "ISO-alpha3 Code": "MCO",
      "name_pt": "Mônaco"
    },
    {
      "name_es": "Países Bajos (Reino de los)",
      "name_ar": "هولندا (مملكة _)",
      "name_fr": "Pays-Bas (Royaume des)",
      "name_zh": "荷兰王国",
      "name_ru": "Нидерланды (Королевство)",
      "name_en": "Netherlands (Kingdom of the)",
      "M49 Code": 528,
      "ISO-alpha2 Code": "NL",
      "ISO-alpha3 Code": "NLD",
      "name_pt": "Países Baixos (Reino dos)"
    },
    {
      "name_es": "Suiza",
      "name_ar": "سويسرا",
      "name_fr": "Suisse",
      "name_zh": "瑞士",
      "name_ru": "Швейцария",
      "name_en": "Switzerland",
      "M49 Code": 756,
      "ISO-alpha2 Code": "CH",
      "ISO-alpha3 Code": "CHE",
      "name_pt": "Suíça"
    },
    {
      "name_es": "Australia",
      "name_ar": "أستراليا",
      "name_fr": "Australie",
      "name_zh": "澳大利亚",
      "name_ru": "Австралия",
      "name_en": "Australia",
      "M49 Code": 36,
      "ISO-alpha2 Code": "AU",
      "ISO-alpha3 Code": "AUS",
      "name_pt": "Austrália"
    },
    {
      "name_es": "Isla Christmas",
      "name_ar": "جزيرة عيد الميلاد",
      "name_fr": "Île Christmas",
      "name_zh": "圣诞岛",
      "name_ru": "остров Рождества",
      "name_en": "Christmas Island",
      "M49 Code": 162,
      "ISO-alpha2 Code": "CX",
      "ISO-alpha3 Code": "CXR",
      "name_pt": "Ilha Christmas"
    },
    {
      "name_es": "Islas Cocos (Keeling)",
      "name_ar": "جزر كوكس (كيلينغ)",
      "name_fr": "Îles des Cocos (Keeling)",
      "name_zh": "科科斯（基林）群岛",
      "name_ru": "Кокосовых (Килинг) островов",
      "name_en": "Cocos (Keeling) Islands",
      "M49 Code": 166,
      "ISO-alpha2 Code": "CC",
      "ISO-alpha3 Code": "CCK",
      "name_pt": "Ilhas Cocos (Keeling)"
    },
    {
      "name_es": "Islas Heard y McDonald",
      "name_ar": "جزيرة هيرد وجزر ماكدونالد",
      "name_fr": "Île Heard-et-Îles MacDonald",
      "name_zh": "赫德岛和麦克唐纳岛",
      "name_ru": "Остров Херд и острова Макдональд",
      "name_en": "Heard Island and McDonald Islands",
      "M49 Code": 334,
      "ISO-alpha2 Code": "HM",
      "ISO-alpha3 Code": "HMD",
      "name_pt": "Ilha Heard e Ilhas McDonald"
    },
    {
      "name_es": "Nueva Zelandia",
      "name_ar": "نيوزيلندا",
      "name_fr": "Nouvelle-Zélande",
      "name_zh": "新西兰",
      "name_ru": "Новая Зеландия",
      "name_en": "New Zealand",
      "M49 Code": 554,
      "ISO-alpha2 Code": "NZ",
      "ISO-alpha3 Code": "NZL",
      "name_pt": "Nova Zelândia"
    },
    {
      "name_es": "Isla Norfolk",
      "name_ar": "جزيرة نورفولك",
      "name_fr": "Île Norfolk",
      "name_zh": "诺福克岛",
      "name_ru": "Остров Норфолк",
      "name_en": "Norfolk Island",
      "M49 Code": 574,
      "ISO-alpha2 Code": "NF",
      "ISO-alpha3 Code": "NFK",
      "name_pt": "Ilha Norfolk"
    },
    {
      "name_es": "Fiji",
      "name_ar": "فيجي",
      "name_fr": "Fidji",
      "name_zh": "斐济",
      "name_ru": "Фиджи",
      "name_en": "Fiji",
      "M49 Code": 242,
      "ISO-alpha2 Code": "FJ",
      "ISO-alpha3 Code": "FJI",
      "name_pt": "Fiji"
    },
    {
      "name_es": "Nueva Caledonia",
      "name_ar": "كاليدونيا الجديدة",
      "name_fr": "Nouvelle-Calédonie",
      "name_zh": "新喀里多尼亚",
      "name_ru": "Новая Каледония",
      "name_en": "New Caledonia",
      "M49 Code": 540,
      "ISO-alpha2 Code": "NC",
      "ISO-alpha3 Code": "NCL",
      "name_pt": "Nova Caledônia"
    },
    {
      "name_es": "Papua Nueva Guinea",
      "name_ar": "بابوا غينيا الجديدة",
      "name_fr": "Papouasie-Nouvelle-Guinée",
      "name_zh": "巴布亚新几内亚",
      "name_ru": "Папуа-Новая Гвинея",
      "name_en": "Papua New Guinea",
      "M49 Code": 598,
      "ISO-alpha2 Code": "PG",
      "ISO-alpha3 Code": "PNG",
      "name_pt": "Papua-Nova Guiné"
    },
    {
      "name_es": "Islas Salomón",
      "name_ar": "جزر سليمان",
      "name_fr": "Îles Salomon",
      "name_zh": "所罗门群岛",
      "name_ru": "Соломоновы Острова",
      "name_en": "Solomon Islands",
      "M49 Code": 90,
      "ISO-alpha2 Code": "SB",
      "ISO-alpha3 Code": "SLB",
      "name_pt": "Ilhas Salomão"
    },
    {
      "name_es": "Vanuatu",
      "name_ar": "فانواتو",
      "name_fr": "Vanuatu",
      "name_zh": "瓦努阿图",
      "name_ru": "Вануату",
      "name_en": "Vanuatu",
      "M49 Code": 548,
      "ISO-alpha2 Code": "VU",
      "ISO-alpha3 Code": "VUT",
      "name_pt": "Vanuatu"
    },
    {
      "name_es": "Guam",
      "name_ar": "غوام",
      "name_fr": "Guam",
      "name_zh": "关岛",
      "name_ru": "Гуам",
      "name_en": "Guam",
      "M49 Code": 316,
      "ISO-alpha2 Code": "GU",
      "ISO-alpha3 Code": "GUM",
      "name_pt": "Guam"
    },
    {
      "name_es": "Kiribati",
      "name_ar": "كيريباس",
      "name_fr": "Kiribati",
      "name_zh": "基里巴斯",
      "name_ru": "Кирибати",
      "name_en": "Kiribati",
      "M49 Code": 296,
      "ISO-alpha2 Code": "KI",
      "ISO-alpha3 Code": "KIR",
      "name_pt": "Quiribati"
    },
    {
      "name_es": "Islas Marshall",
      "name_ar": "جزر مارشال",
      "name_fr": "Îles Marshall",
      "name_zh": "马绍尔群岛",
      "name_ru": "Маршалловы Острова",
      "name_en": "Marshall Islands",
      "M49 Code": 584,
      "ISO-alpha2 Code": "MH",
      "ISO-alpha3 Code": "MHL",
      "name_pt": "Ilhas Marshall"
    },
    {
      "name_es": "Micronesia (Estados Federados de)",
      "name_ar": "ميكرونيزيا (ولايات - الموحدة)",
      "name_fr": "Micronésie (États fédérés de)",
      "name_zh": "密克罗尼西亚联邦",
      "name_ru": "Микронезия (Федеративные Штаты)",
      "name_en": "Micronesia (Federated States of)",
      "M49 Code": 583,
      "ISO-alpha2 Code": "FM",
      "ISO-alpha3 Code": "FSM",
      "name_pt": "Micronésia (Estados Federados da)"
    },
    {
      "name_es": "Nauru",
      "name_ar": "ناورو",
      "name_fr": "Nauru",
      "name_zh": "瑙鲁",
      "name_ru": "Науру",
      "name_en": "Nauru",
      "M49 Code": 520,
      "ISO-alpha2 Code": "NR",
      "ISO-alpha3 Code": "NRU",
      "name_pt": "Nauru"
    },
    {
      "name_es": "Islas Marianas Septentrionales",
      "name_ar": "جزر ماريانا الشمالية",
      "name_fr": "Îles Mariannes du Nord",
      "name_zh": "北马里亚纳群岛",
      "name_ru": "Северные Марианские острова",
      "name_en": "Northern Mariana Islands",
      "M49 Code": 580,
      "ISO-alpha2 Code": "MP",
      "ISO-alpha3 Code": "MNP",
      "name_pt": "Ilhas Marianas do Norte"
    },
    {
      "name_es": "Palau",
      "name_ar": "بالاو",
      "name_fr": "Palaos",
      "name_zh": "帕劳",
      "name_ru": "Палау",
      "name_en": "Palau",
      "M49 Code": 585,
      "ISO-alpha2 Code": "PW",
      "ISO-alpha3 Code": "PLW",
      "name_pt": "Palau"
    },
    {
      "name_es": "Islas menores alejadas de Estados Unidos",
      "name_ar": "نائية التابعة للولايات المتحدة",
      "name_fr": "Îles mineures éloignées des États-Unis",
      "name_zh": "美国本土外小岛屿",
      "name_ru": "Внешние малые острова Соединенных Штатов",
      "name_en": "United States Minor Outlying Islands",
      "M49 Code": 581,
      "ISO-alpha2 Code": "UM",
      "ISO-alpha3 Code": "UMI",
      "name_pt": "Ilhas Menores Distantes dos Estados Unidos"
    },
    {
      "name_es": "Samoa Americana",
      "name_ar": "ساموا الأمريكية",
      "name_fr": "Samoa américaines",
      "name_zh": "美属萨摩亚",
      "name_ru": "Американское Самоа",
      "name_en": "American Samoa",
      "M49 Code": 16,
      "ISO-alpha2 Code": "AS",
      "ISO-alpha3 Code": "ASM",
      "name_pt": "Samoa Americana"
    },
    {
      "name_es": "Islas Cook",
      "name_ar": "جزر كوك",
      "name_fr": "Îles Cook",
      "name_zh": "库克群岛",
      "name_ru": "Острова Кука",
      "name_en": "Cook Islands",
      "M49 Code": 184,
      "ISO-alpha2 Code": "CK",
      "ISO-alpha3 Code": "COK",
      "name_pt": "Ilhas Cook"
    },
    {
      "name_es": "Polinesia Francesa",
      "name_ar": "بولينيزيا الفرنسية",
      "name_fr": "Polynésie française",
      "name_zh": "法属波利尼西亚",
      "name_ru": "Французская Полинезия",
      "name_en": "French Polynesia",
      "M49 Code": 258,
      "ISO-alpha2 Code": "PF",
      "ISO-alpha3 Code": "PYF",
      "name_pt": "Polinésia Francesa"
    },
    {
      "name_es": "Niue",
      "name_ar": "نيوي",
      "name_fr": "Nioué",
      "name_zh": "纽埃",
      "name_ru": "Ниуэ",
      "name_en": "Niue",
      "M49 Code": 570,
      "ISO-alpha2 Code": "NU",
      "ISO-alpha3 Code": "NIU",
      "name_pt": "Niue"
    },
    {
      "name_es": "Pitcairn",
      "name_ar": "بيتكرن",
      "name_fr": "Pitcairn",
      "name_zh": "皮特凯恩",
      "name_ru": "Питкэрн",
      "name_en": "Pitcairn",
      "M49 Code": 612,
      "ISO-alpha2 Code": "PN",
      "ISO-alpha3 Code": "PCN",
      "name_pt": "Pitcairn"
    },
    {
      "name_es": "Samoa",
      "name_ar": "ساموا",
      "name_fr": "Samoa",
      "name_zh": "萨摩亚",
      "name_ru": "Самоа",
      "name_en": "Samoa",
      "M49 Code": 882,
      "ISO-alpha2 Code": "WS",
      "ISO-alpha3 Code": "WSM",
      "name_pt": "Samoa"
    },
    {
      "name_es": "Tokelau",
      "name_ar": "توكيلاو",
      "name_fr": "Tokélaou",
      "name_zh": "托克劳",
      "name_ru": "Токелау",
      "name_en": "Tokelau",
      "M49 Code": 772,
      "ISO-alpha2 Code": "TK",
      "ISO-alpha3 Code": "TKL",
      "name_pt": "Tokelau"
    },
    {
      "name_es": "Tonga",
      "name_ar": "تونغا",
      "name_fr": "Tonga",
      "name_zh": "汤加",
      "name_ru": "Тонга",
      "name_en": "Tonga",
      "M49 Code": 776,
      "ISO-alpha2 Code": "TO",
      "ISO-alpha3 Code": "TON",
      "name_pt": "Tonga"
    },
    {
      "name_es": "Tuvalu",
      "name_ar": "توفالو",
      "name_fr": "Tuvalu",
      "name_zh": "图瓦卢",
      "name_ru": "Тувалу",
      "name_en": "Tuvalu",
      "M49 Code": 798,
      "ISO-alpha2 Code": "TV",
      "ISO-alpha3 Code": "TUV",
      "name_pt": "Tuvalu"
    },
    {
      "name_es": "Islas Wallis y Futuna",
      "name_ar": "جزر واليس وفوتونا",
      "name_fr": "Îles Wallis-et-Futuna",
      "name_zh": "瓦利斯群岛和富图纳群岛",
      "name_ru": "Острова Уоллис и Футуна",
      "name_en": "Wallis and Futuna Islands",
      "M49 Code": 876,
      "ISO-alpha2 Code": "WF",
      "ISO-alpha3 Code": "WLF",
      "name_pt": "Ilhas Wallis e Futuna"
    },
    {
      "name_es": "Taiwán (Provincia de China)",
      "name_ar": "تايوان (مقاطعة الصين)",
      "name_fr": "Taïwan (Province de Chine)",
      "name_zh": "中国台湾省",
      "name_ru": "Тайвань (Провинция Китая)",
      "name_en": "Taiwan (Province of China)",
      "M49 Code": 158,
      "ISO-alpha2 Code": "TW",
      "ISO-alpha3 Code": "TWN",
      "name_pt": "Taiwan (Província da China)"
    }
  ];
  static Map<String, dynamic>? _findByIso2(String iso2) {
    final upperIso2 = iso2.toUpperCase();
    try {
      return _countries.firstWhere(
        (country) =>
            (country["ISO-alpha2 Code"] as String?)?.toUpperCase() == upperIso2,
      );
    } catch (e) {
      return null;
    }
  }

  static Map<String, dynamic>? _findByIso3(String iso3) {
    final upperIso3 = iso3.toUpperCase();
    try {
      return _countries.firstWhere(
        (country) =>
            (country["ISO-alpha3 Code"] as String?)?.toUpperCase() == upperIso3,
      );
    } catch (e) {
      return null;
    }
  }

  static Map<String, dynamic>? _findByM49(int m49Code) {
    try {
      return _countries.firstWhere(
        (country) => (country["M49 Code"] as int?) == m49Code,
      );
    } catch (e) {
      return null;
    }
  }

  static String? getName(String iso2, {String languageCode = 'en'}) {
    final country = _findByIso2(iso2);
    if (country == null) return null;

    switch (languageCode.toLowerCase()) {
      case 'en':
        return country['name_en'] as String?;
      case 'es':
        return country['name_es'] as String?;
      case 'fr':
        return country['name_fr'] as String?;
      case 'ru':
        return country['name_ru'] as String?;
      case 'pt':
        return country['name_pt'] as String?;
      case 'zh':
        return country['name_zh'] as String?;
      case 'ar':
        return country['name_ar'] as String?;
      default:
        return country['name_en'] as String?;
    }
  }

  static Map<String, String> getAllNames({String languageCode = 'en'}) {
    final result = <String, String>{};
    for (final country in _countries) {
      final iso2 = country['ISO-alpha2 Code'] as String?;
      if (iso2 != null && iso2.isNotEmpty) {
        final name = getName(iso2, languageCode: languageCode);
        if (name != null) {
          result[iso2] = name;
        }
      }
    }
    return result;
  }

  static String? getNameByM49Code(int m49Code, {String languageCode = 'en'}) {
    final country = _findByM49(m49Code);
    if (country == null) return null;

    switch (languageCode.toLowerCase()) {
      case 'en':
        return country['name_en'] as String?;
      case 'es':
        return country['name_es'] as String?;
      case 'fr':
        return country['name_fr'] as String?;
      case 'ru':
        return country['name_ru'] as String?;
      case 'pt':
        return country['name_pt'] as String?;
      case 'zh':
        return country['name_zh'] as String?;
      case 'ar':
        return country['name_ar'] as String?;
      default:
        return country['name_en'] as String?;
    }
  }

  static String? getIso2FromIso3(String iso3) {
    final country = _findByIso3(iso3);
    return country?['ISO-alpha2 Code'] as String?;
  }

  static String? getIso2FromM49(int m49Code) {
    final country = _findByM49(m49Code);
    return country?['ISO-alpha2 Code'] as String?;
  }
}
